package com.pratz.dao.table.mapper;

import com.pratz.dao.table.model.AdministrableRoleAuthorizations;
import com.pratz.dao.table.model.AdministrableRoleAuthorizationsCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdministrableRoleAuthorizationsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.ADMINISTRABLE_ROLE_AUTHORIZATIONS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int countByExample(AdministrableRoleAuthorizationsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.ADMINISTRABLE_ROLE_AUTHORIZATIONS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int deleteByExample(AdministrableRoleAuthorizationsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.ADMINISTRABLE_ROLE_AUTHORIZATIONS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int insert(AdministrableRoleAuthorizations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.ADMINISTRABLE_ROLE_AUTHORIZATIONS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int insertSelective(AdministrableRoleAuthorizations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.ADMINISTRABLE_ROLE_AUTHORIZATIONS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    List<AdministrableRoleAuthorizations> selectByExample(AdministrableRoleAuthorizationsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.ADMINISTRABLE_ROLE_AUTHORIZATIONS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int updateByExampleSelective(@Param("record") AdministrableRoleAuthorizations record, @Param("example") AdministrableRoleAuthorizationsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.ADMINISTRABLE_ROLE_AUTHORIZATIONS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int updateByExample(@Param("record") AdministrableRoleAuthorizations record, @Param("example") AdministrableRoleAuthorizationsCriteria example);
}