package com.pratz.dao.table.mapper;

import com.pratz.dao.table.model.ConstraintTableUsage;
import com.pratz.dao.table.model.ConstraintTableUsageCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConstraintTableUsageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.CONSTRAINT_TABLE_USAGE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int countByExample(ConstraintTableUsageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.CONSTRAINT_TABLE_USAGE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int deleteByExample(ConstraintTableUsageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.CONSTRAINT_TABLE_USAGE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int insert(ConstraintTableUsage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.CONSTRAINT_TABLE_USAGE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int insertSelective(ConstraintTableUsage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.CONSTRAINT_TABLE_USAGE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    List<ConstraintTableUsage> selectByExample(ConstraintTableUsageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.CONSTRAINT_TABLE_USAGE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int updateByExampleSelective(@Param("record") ConstraintTableUsage record, @Param("example") ConstraintTableUsageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.CONSTRAINT_TABLE_USAGE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int updateByExample(@Param("record") ConstraintTableUsage record, @Param("example") ConstraintTableUsageCriteria example);
}