package com.pratz.dao.table.mapper;

import com.pratz.dao.table.model.ConstraintColumnUsage;
import com.pratz.dao.table.model.ConstraintColumnUsageCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConstraintColumnUsageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int countByExample(ConstraintColumnUsageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int deleteByExample(ConstraintColumnUsageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int insert(ConstraintColumnUsage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int insertSelective(ConstraintColumnUsage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    List<ConstraintColumnUsage> selectByExample(ConstraintColumnUsageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int updateByExampleSelective(@Param("record") ConstraintColumnUsage record, @Param("example") ConstraintColumnUsageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int updateByExample(@Param("record") ConstraintColumnUsage record, @Param("example") ConstraintColumnUsageCriteria example);
}