package com.pratz.dao.table.mapper;

import com.pratz.dao.table.model.DataTypePrivileges;
import com.pratz.dao.table.model.DataTypePrivilegesCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DataTypePrivilegesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.DATA_TYPE_PRIVILEGES
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int countByExample(DataTypePrivilegesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.DATA_TYPE_PRIVILEGES
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int deleteByExample(DataTypePrivilegesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.DATA_TYPE_PRIVILEGES
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int insert(DataTypePrivileges record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.DATA_TYPE_PRIVILEGES
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int insertSelective(DataTypePrivileges record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.DATA_TYPE_PRIVILEGES
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    List<DataTypePrivileges> selectByExample(DataTypePrivilegesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.DATA_TYPE_PRIVILEGES
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int updateByExampleSelective(@Param("record") DataTypePrivileges record, @Param("example") DataTypePrivilegesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.DATA_TYPE_PRIVILEGES
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int updateByExample(@Param("record") DataTypePrivileges record, @Param("example") DataTypePrivilegesCriteria example);
}