package com.pratz.dao.table.mapper;

import com.pratz.dao.table.model.DomainConstraints;
import com.pratz.dao.table.model.DomainConstraintsCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DomainConstraintsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.DOMAIN_CONSTRAINTS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int countByExample(DomainConstraintsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.DOMAIN_CONSTRAINTS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int deleteByExample(DomainConstraintsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.DOMAIN_CONSTRAINTS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int insert(DomainConstraints record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.DOMAIN_CONSTRAINTS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int insertSelective(DomainConstraints record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.DOMAIN_CONSTRAINTS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    List<DomainConstraints> selectByExample(DomainConstraintsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.DOMAIN_CONSTRAINTS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int updateByExampleSelective(@Param("record") DomainConstraints record, @Param("example") DomainConstraintsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.DOMAIN_CONSTRAINTS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int updateByExample(@Param("record") DomainConstraints record, @Param("example") DomainConstraintsCriteria example);
}