package com.pratz.dao.table.mapper;

import com.pratz.dao.table.model.EnabledRoles;
import com.pratz.dao.table.model.EnabledRolesCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EnabledRolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.ENABLED_ROLES
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int countByExample(EnabledRolesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.ENABLED_ROLES
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int deleteByExample(EnabledRolesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.ENABLED_ROLES
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int insert(EnabledRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.ENABLED_ROLES
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int insertSelective(EnabledRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.ENABLED_ROLES
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    List<EnabledRoles> selectByExample(EnabledRolesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.ENABLED_ROLES
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int updateByExampleSelective(@Param("record") EnabledRoles record, @Param("example") EnabledRolesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.ENABLED_ROLES
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int updateByExample(@Param("record") EnabledRoles record, @Param("example") EnabledRolesCriteria example);
}