package com.pratz.dao.table.mapper;

import com.pratz.dao.table.model.Lobs;
import com.pratz.dao.table.model.LobsCriteria;
import com.pratz.dao.table.model.LobsKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LobsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_LOBS.LOBS
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    int countByExample(LobsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_LOBS.LOBS
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    int deleteByExample(LobsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_LOBS.LOBS
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    int deleteByPrimaryKey(LobsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_LOBS.LOBS
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    int insert(Lobs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_LOBS.LOBS
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    int insertSelective(Lobs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_LOBS.LOBS
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    List<Lobs> selectByExample(LobsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_LOBS.LOBS
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    Lobs selectByPrimaryKey(LobsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_LOBS.LOBS
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    int updateByExampleSelective(@Param("record") Lobs record, @Param("example") LobsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_LOBS.LOBS
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    int updateByExample(@Param("record") Lobs record, @Param("example") LobsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_LOBS.LOBS
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    int updateByPrimaryKeySelective(Lobs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_LOBS.LOBS
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    int updateByPrimaryKey(Lobs record);
}