package com.pratz.dao.table.mapper;

import com.pratz.dao.table.model.ReferentialConstraints;
import com.pratz.dao.table.model.ReferentialConstraintsCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReferentialConstraintsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int countByExample(ReferentialConstraintsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int deleteByExample(ReferentialConstraintsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int insert(ReferentialConstraints record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int insertSelective(ReferentialConstraints record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    List<ReferentialConstraints> selectByExample(ReferentialConstraintsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int updateByExampleSelective(@Param("record") ReferentialConstraints record, @Param("example") ReferentialConstraintsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int updateByExample(@Param("record") ReferentialConstraints record, @Param("example") ReferentialConstraintsCriteria example);
}