package com.pratz.dao.table.mapper;

import com.pratz.dao.table.model.RoleUdtGrants;
import com.pratz.dao.table.model.RoleUdtGrantsCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleUdtGrantsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.ROLE_UDT_GRANTS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int countByExample(RoleUdtGrantsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.ROLE_UDT_GRANTS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int deleteByExample(RoleUdtGrantsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.ROLE_UDT_GRANTS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int insert(RoleUdtGrants record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.ROLE_UDT_GRANTS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int insertSelective(RoleUdtGrants record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.ROLE_UDT_GRANTS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    List<RoleUdtGrants> selectByExample(RoleUdtGrantsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.ROLE_UDT_GRANTS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int updateByExampleSelective(@Param("record") RoleUdtGrants record, @Param("example") RoleUdtGrantsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.ROLE_UDT_GRANTS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int updateByExample(@Param("record") RoleUdtGrants record, @Param("example") RoleUdtGrantsCriteria example);
}