package com.pratz.dao.table.mapper;

import com.pratz.dao.table.model.RoutineTableUsage;
import com.pratz.dao.table.model.RoutineTableUsageCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoutineTableUsageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.ROUTINE_TABLE_USAGE
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    int countByExample(RoutineTableUsageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.ROUTINE_TABLE_USAGE
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    int deleteByExample(RoutineTableUsageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.ROUTINE_TABLE_USAGE
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    int insert(RoutineTableUsage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.ROUTINE_TABLE_USAGE
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    int insertSelective(RoutineTableUsage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.ROUTINE_TABLE_USAGE
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    List<RoutineTableUsage> selectByExample(RoutineTableUsageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.ROUTINE_TABLE_USAGE
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    int updateByExampleSelective(@Param("record") RoutineTableUsage record, @Param("example") RoutineTableUsageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.ROUTINE_TABLE_USAGE
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    int updateByExample(@Param("record") RoutineTableUsage record, @Param("example") RoutineTableUsageCriteria example);
}