package com.pratz.dao.table.mapper;

import com.pratz.dao.table.model.SystemProcedurecolumns;
import com.pratz.dao.table.model.SystemProcedurecolumnsCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SystemProcedurecolumnsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_PROCEDURECOLUMNS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int countByExample(SystemProcedurecolumnsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_PROCEDURECOLUMNS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int deleteByExample(SystemProcedurecolumnsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_PROCEDURECOLUMNS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int insert(SystemProcedurecolumns record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_PROCEDURECOLUMNS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int insertSelective(SystemProcedurecolumns record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_PROCEDURECOLUMNS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    List<SystemProcedurecolumns> selectByExample(SystemProcedurecolumnsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_PROCEDURECOLUMNS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int updateByExampleSelective(@Param("record") SystemProcedurecolumns record, @Param("example") SystemProcedurecolumnsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_PROCEDURECOLUMNS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int updateByExample(@Param("record") SystemProcedurecolumns record, @Param("example") SystemProcedurecolumnsCriteria example);
}