package com.pratz.dao.table.mapper;

import com.pratz.dao.table.model.SystemBestrowidentifier;
import com.pratz.dao.table.model.SystemBestrowidentifierCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SystemBestrowidentifierMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_BESTROWIDENTIFIER
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int countByExample(SystemBestrowidentifierCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_BESTROWIDENTIFIER
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int deleteByExample(SystemBestrowidentifierCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_BESTROWIDENTIFIER
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int insert(SystemBestrowidentifier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_BESTROWIDENTIFIER
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int insertSelective(SystemBestrowidentifier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_BESTROWIDENTIFIER
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    List<SystemBestrowidentifier> selectByExample(SystemBestrowidentifierCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_BESTROWIDENTIFIER
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int updateByExampleSelective(@Param("record") SystemBestrowidentifier record, @Param("example") SystemBestrowidentifierCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_BESTROWIDENTIFIER
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int updateByExample(@Param("record") SystemBestrowidentifier record, @Param("example") SystemBestrowidentifierCriteria example);
}