package com.pratz.dao.table.mapper;

import com.pratz.dao.table.model.SystemConnectionProperties;
import com.pratz.dao.table.model.SystemConnectionPropertiesCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SystemConnectionPropertiesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_CONNECTION_PROPERTIES
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int countByExample(SystemConnectionPropertiesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_CONNECTION_PROPERTIES
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int deleteByExample(SystemConnectionPropertiesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_CONNECTION_PROPERTIES
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int insert(SystemConnectionProperties record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_CONNECTION_PROPERTIES
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int insertSelective(SystemConnectionProperties record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_CONNECTION_PROPERTIES
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    List<SystemConnectionProperties> selectByExample(SystemConnectionPropertiesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_CONNECTION_PROPERTIES
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int updateByExampleSelective(@Param("record") SystemConnectionProperties record, @Param("example") SystemConnectionPropertiesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_CONNECTION_PROPERTIES
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int updateByExample(@Param("record") SystemConnectionProperties record, @Param("example") SystemConnectionPropertiesCriteria example);
}