package com.pratz.dao.table.mapper;

import com.pratz.dao.table.model.SystemCrossreference;
import com.pratz.dao.table.model.SystemCrossreferenceCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SystemCrossreferenceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_CROSSREFERENCE
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    int countByExample(SystemCrossreferenceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_CROSSREFERENCE
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    int deleteByExample(SystemCrossreferenceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_CROSSREFERENCE
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    int insert(SystemCrossreference record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_CROSSREFERENCE
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    int insertSelective(SystemCrossreference record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_CROSSREFERENCE
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    List<SystemCrossreference> selectByExample(SystemCrossreferenceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_CROSSREFERENCE
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    int updateByExampleSelective(@Param("record") SystemCrossreference record, @Param("example") SystemCrossreferenceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_CROSSREFERENCE
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    int updateByExample(@Param("record") SystemCrossreference record, @Param("example") SystemCrossreferenceCriteria example);
}