package com.pratz.dao.table.mapper;

import com.pratz.dao.table.model.SystemPrimarykeys;
import com.pratz.dao.table.model.SystemPrimarykeysCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SystemPrimarykeysMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_PRIMARYKEYS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int countByExample(SystemPrimarykeysCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_PRIMARYKEYS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int deleteByExample(SystemPrimarykeysCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_PRIMARYKEYS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int insert(SystemPrimarykeys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_PRIMARYKEYS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int insertSelective(SystemPrimarykeys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_PRIMARYKEYS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    List<SystemPrimarykeys> selectByExample(SystemPrimarykeysCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_PRIMARYKEYS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int updateByExampleSelective(@Param("record") SystemPrimarykeys record, @Param("example") SystemPrimarykeysCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_PRIMARYKEYS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int updateByExample(@Param("record") SystemPrimarykeys record, @Param("example") SystemPrimarykeysCriteria example);
}