package com.pratz.dao.table.mapper;

import com.pratz.dao.table.model.SystemIndexinfo;
import com.pratz.dao.table.model.SystemIndexinfoCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SystemIndexinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_INDEXINFO
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    int countByExample(SystemIndexinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_INDEXINFO
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    int deleteByExample(SystemIndexinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_INDEXINFO
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    int insert(SystemIndexinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_INDEXINFO
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    int insertSelective(SystemIndexinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_INDEXINFO
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    List<SystemIndexinfo> selectByExample(SystemIndexinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_INDEXINFO
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    int updateByExampleSelective(@Param("record") SystemIndexinfo record, @Param("example") SystemIndexinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_INDEXINFO
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    int updateByExample(@Param("record") SystemIndexinfo record, @Param("example") SystemIndexinfoCriteria example);
}