package com.pratz.dao.table.mapper;

import com.pratz.dao.table.model.TriggeredUpdateColumns;
import com.pratz.dao.table.model.TriggeredUpdateColumnsCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TriggeredUpdateColumnsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.TRIGGERED_UPDATE_COLUMNS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int countByExample(TriggeredUpdateColumnsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.TRIGGERED_UPDATE_COLUMNS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int deleteByExample(TriggeredUpdateColumnsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.TRIGGERED_UPDATE_COLUMNS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int insert(TriggeredUpdateColumns record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.TRIGGERED_UPDATE_COLUMNS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int insertSelective(TriggeredUpdateColumns record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.TRIGGERED_UPDATE_COLUMNS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    List<TriggeredUpdateColumns> selectByExample(TriggeredUpdateColumnsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.TRIGGERED_UPDATE_COLUMNS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int updateByExampleSelective(@Param("record") TriggeredUpdateColumns record, @Param("example") TriggeredUpdateColumnsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.TRIGGERED_UPDATE_COLUMNS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int updateByExample(@Param("record") TriggeredUpdateColumns record, @Param("example") TriggeredUpdateColumnsCriteria example);
}