package com.pratz.dao.table.mapper;

import com.pratz.dao.table.model.TTrQuotationno;
import com.pratz.dao.table.model.TTrQuotationnoCriteria;
import com.pratz.dao.table.model.TTrQuotationnoKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TTrQuotationnoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTFL.T_TR_QUOTATIONNO
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int countByExample(TTrQuotationnoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTFL.T_TR_QUOTATIONNO
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int deleteByExample(TTrQuotationnoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTFL.T_TR_QUOTATIONNO
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int deleteByPrimaryKey(TTrQuotationnoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTFL.T_TR_QUOTATIONNO
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int insert(TTrQuotationno record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTFL.T_TR_QUOTATIONNO
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int insertSelective(TTrQuotationno record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTFL.T_TR_QUOTATIONNO
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    List<TTrQuotationno> selectByExample(TTrQuotationnoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTFL.T_TR_QUOTATIONNO
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    TTrQuotationno selectByPrimaryKey(TTrQuotationnoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTFL.T_TR_QUOTATIONNO
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int updateByExampleSelective(@Param("record") TTrQuotationno record, @Param("example") TTrQuotationnoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTFL.T_TR_QUOTATIONNO
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int updateByExample(@Param("record") TTrQuotationno record, @Param("example") TTrQuotationnoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTFL.T_TR_QUOTATIONNO
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int updateByPrimaryKeySelective(TTrQuotationno record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTFL.T_TR_QUOTATIONNO
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int updateByPrimaryKey(TTrQuotationno record);
}