package com.pratz.dao.table.mapper;

import com.pratz.dao.table.model.UdtPrivileges;
import com.pratz.dao.table.model.UdtPrivilegesCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UdtPrivilegesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.UDT_PRIVILEGES
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int countByExample(UdtPrivilegesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.UDT_PRIVILEGES
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int deleteByExample(UdtPrivilegesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.UDT_PRIVILEGES
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int insert(UdtPrivileges record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.UDT_PRIVILEGES
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int insertSelective(UdtPrivileges record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.UDT_PRIVILEGES
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    List<UdtPrivileges> selectByExample(UdtPrivilegesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.UDT_PRIVILEGES
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int updateByExampleSelective(@Param("record") UdtPrivileges record, @Param("example") UdtPrivilegesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.UDT_PRIVILEGES
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    int updateByExample(@Param("record") UdtPrivileges record, @Param("example") UdtPrivilegesCriteria example);
}