package com.pratz.dao.table.model;

public class ColumnDomainUsage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.COLUMN_DOMAIN_USAGE.DOMAIN_CATALOG
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String domainCatalog;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.COLUMN_DOMAIN_USAGE.DOMAIN_SCHEMA
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String domainSchema;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.COLUMN_DOMAIN_USAGE.DOMAIN_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String domainName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.COLUMN_DOMAIN_USAGE.TABLE_CATALOG
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String tableCatalog;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.COLUMN_DOMAIN_USAGE.TABLE_SCHEMA
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String tableSchema;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.COLUMN_DOMAIN_USAGE.TABLE_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String tableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.COLUMN_DOMAIN_USAGE.COLUMN_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String columnName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.COLUMN_DOMAIN_USAGE.DOMAIN_CATALOG
     *
     * @return the value of INFORMATION_SCHEMA.COLUMN_DOMAIN_USAGE.DOMAIN_CATALOG
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getDomainCatalog() {
        return domainCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.COLUMN_DOMAIN_USAGE.DOMAIN_CATALOG
     *
     * @param domainCatalog the value for INFORMATION_SCHEMA.COLUMN_DOMAIN_USAGE.DOMAIN_CATALOG
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setDomainCatalog(String domainCatalog) {
        this.domainCatalog = domainCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.COLUMN_DOMAIN_USAGE.DOMAIN_SCHEMA
     *
     * @return the value of INFORMATION_SCHEMA.COLUMN_DOMAIN_USAGE.DOMAIN_SCHEMA
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getDomainSchema() {
        return domainSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.COLUMN_DOMAIN_USAGE.DOMAIN_SCHEMA
     *
     * @param domainSchema the value for INFORMATION_SCHEMA.COLUMN_DOMAIN_USAGE.DOMAIN_SCHEMA
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setDomainSchema(String domainSchema) {
        this.domainSchema = domainSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.COLUMN_DOMAIN_USAGE.DOMAIN_NAME
     *
     * @return the value of INFORMATION_SCHEMA.COLUMN_DOMAIN_USAGE.DOMAIN_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getDomainName() {
        return domainName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.COLUMN_DOMAIN_USAGE.DOMAIN_NAME
     *
     * @param domainName the value for INFORMATION_SCHEMA.COLUMN_DOMAIN_USAGE.DOMAIN_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setDomainName(String domainName) {
        this.domainName = domainName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.COLUMN_DOMAIN_USAGE.TABLE_CATALOG
     *
     * @return the value of INFORMATION_SCHEMA.COLUMN_DOMAIN_USAGE.TABLE_CATALOG
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getTableCatalog() {
        return tableCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.COLUMN_DOMAIN_USAGE.TABLE_CATALOG
     *
     * @param tableCatalog the value for INFORMATION_SCHEMA.COLUMN_DOMAIN_USAGE.TABLE_CATALOG
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setTableCatalog(String tableCatalog) {
        this.tableCatalog = tableCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.COLUMN_DOMAIN_USAGE.TABLE_SCHEMA
     *
     * @return the value of INFORMATION_SCHEMA.COLUMN_DOMAIN_USAGE.TABLE_SCHEMA
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getTableSchema() {
        return tableSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.COLUMN_DOMAIN_USAGE.TABLE_SCHEMA
     *
     * @param tableSchema the value for INFORMATION_SCHEMA.COLUMN_DOMAIN_USAGE.TABLE_SCHEMA
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setTableSchema(String tableSchema) {
        this.tableSchema = tableSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.COLUMN_DOMAIN_USAGE.TABLE_NAME
     *
     * @return the value of INFORMATION_SCHEMA.COLUMN_DOMAIN_USAGE.TABLE_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.COLUMN_DOMAIN_USAGE.TABLE_NAME
     *
     * @param tableName the value for INFORMATION_SCHEMA.COLUMN_DOMAIN_USAGE.TABLE_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.COLUMN_DOMAIN_USAGE.COLUMN_NAME
     *
     * @return the value of INFORMATION_SCHEMA.COLUMN_DOMAIN_USAGE.COLUMN_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getColumnName() {
        return columnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.COLUMN_DOMAIN_USAGE.COLUMN_NAME
     *
     * @param columnName the value for INFORMATION_SCHEMA.COLUMN_DOMAIN_USAGE.COLUMN_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setColumnName(String columnName) {
        this.columnName = columnName;
    }
}