package com.pratz.dao.table.model;

public class LobIds {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_LOBS.LOB_IDS.LOB_ID
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private Long lobId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_LOBS.LOB_IDS.LOB_LENGTH
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private Long lobLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_LOBS.LOB_IDS.LOB_USAGE_COUNT
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private Integer lobUsageCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_LOBS.LOB_IDS.LOB_TYPE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private Short lobType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_LOBS.LOB_IDS.LOB_ID
     *
     * @return the value of SYSTEM_LOBS.LOB_IDS.LOB_ID
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public Long getLobId() {
        return lobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_LOBS.LOB_IDS.LOB_ID
     *
     * @param lobId the value for SYSTEM_LOBS.LOB_IDS.LOB_ID
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setLobId(Long lobId) {
        this.lobId = lobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_LOBS.LOB_IDS.LOB_LENGTH
     *
     * @return the value of SYSTEM_LOBS.LOB_IDS.LOB_LENGTH
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public Long getLobLength() {
        return lobLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_LOBS.LOB_IDS.LOB_LENGTH
     *
     * @param lobLength the value for SYSTEM_LOBS.LOB_IDS.LOB_LENGTH
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setLobLength(Long lobLength) {
        this.lobLength = lobLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_LOBS.LOB_IDS.LOB_USAGE_COUNT
     *
     * @return the value of SYSTEM_LOBS.LOB_IDS.LOB_USAGE_COUNT
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public Integer getLobUsageCount() {
        return lobUsageCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_LOBS.LOB_IDS.LOB_USAGE_COUNT
     *
     * @param lobUsageCount the value for SYSTEM_LOBS.LOB_IDS.LOB_USAGE_COUNT
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setLobUsageCount(Integer lobUsageCount) {
        this.lobUsageCount = lobUsageCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_LOBS.LOB_IDS.LOB_TYPE
     *
     * @return the value of SYSTEM_LOBS.LOB_IDS.LOB_TYPE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public Short getLobType() {
        return lobType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_LOBS.LOB_IDS.LOB_TYPE
     *
     * @param lobType the value for SYSTEM_LOBS.LOB_IDS.LOB_TYPE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setLobType(Short lobType) {
        this.lobType = lobType;
    }
}