package com.pratz.dao.table.model;

public class RoleAuthorizationDescriptors {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.ROLE_AUTHORIZATION_DESCRIPTORS.ROLE_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.ROLE_AUTHORIZATION_DESCRIPTORS.GRANTEE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String grantee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.ROLE_AUTHORIZATION_DESCRIPTORS.GRANTOR
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String grantor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.ROLE_AUTHORIZATION_DESCRIPTORS.IS_GRANTABLE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String isGrantable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.ROLE_AUTHORIZATION_DESCRIPTORS.ROLE_NAME
     *
     * @return the value of INFORMATION_SCHEMA.ROLE_AUTHORIZATION_DESCRIPTORS.ROLE_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.ROLE_AUTHORIZATION_DESCRIPTORS.ROLE_NAME
     *
     * @param roleName the value for INFORMATION_SCHEMA.ROLE_AUTHORIZATION_DESCRIPTORS.ROLE_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.ROLE_AUTHORIZATION_DESCRIPTORS.GRANTEE
     *
     * @return the value of INFORMATION_SCHEMA.ROLE_AUTHORIZATION_DESCRIPTORS.GRANTEE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getGrantee() {
        return grantee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.ROLE_AUTHORIZATION_DESCRIPTORS.GRANTEE
     *
     * @param grantee the value for INFORMATION_SCHEMA.ROLE_AUTHORIZATION_DESCRIPTORS.GRANTEE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setGrantee(String grantee) {
        this.grantee = grantee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.ROLE_AUTHORIZATION_DESCRIPTORS.GRANTOR
     *
     * @return the value of INFORMATION_SCHEMA.ROLE_AUTHORIZATION_DESCRIPTORS.GRANTOR
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getGrantor() {
        return grantor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.ROLE_AUTHORIZATION_DESCRIPTORS.GRANTOR
     *
     * @param grantor the value for INFORMATION_SCHEMA.ROLE_AUTHORIZATION_DESCRIPTORS.GRANTOR
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setGrantor(String grantor) {
        this.grantor = grantor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.ROLE_AUTHORIZATION_DESCRIPTORS.IS_GRANTABLE
     *
     * @return the value of INFORMATION_SCHEMA.ROLE_AUTHORIZATION_DESCRIPTORS.IS_GRANTABLE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getIsGrantable() {
        return isGrantable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.ROLE_AUTHORIZATION_DESCRIPTORS.IS_GRANTABLE
     *
     * @param isGrantable the value for INFORMATION_SCHEMA.ROLE_AUTHORIZATION_DESCRIPTORS.IS_GRANTABLE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setIsGrantable(String isGrantable) {
        this.isGrantable = isGrantable;
    }
}