package com.pratz.dao.table.model;

public class RoleColumnGrants {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.ROLE_COLUMN_GRANTS.GRANTOR
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String grantor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.ROLE_COLUMN_GRANTS.GRANTEE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String grantee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.ROLE_COLUMN_GRANTS.TABLE_CATALOG
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String tableCatalog;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.ROLE_COLUMN_GRANTS.TABLE_SCHEMA
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String tableSchema;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.ROLE_COLUMN_GRANTS.TABLE_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String tableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.ROLE_COLUMN_GRANTS.COLUMN_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String columnName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.ROLE_COLUMN_GRANTS.PRIVILEGE_TYPE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String privilegeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.ROLE_COLUMN_GRANTS.IS_GRANTABLE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String isGrantable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.ROLE_COLUMN_GRANTS.GRANTOR
     *
     * @return the value of INFORMATION_SCHEMA.ROLE_COLUMN_GRANTS.GRANTOR
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getGrantor() {
        return grantor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.ROLE_COLUMN_GRANTS.GRANTOR
     *
     * @param grantor the value for INFORMATION_SCHEMA.ROLE_COLUMN_GRANTS.GRANTOR
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setGrantor(String grantor) {
        this.grantor = grantor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.ROLE_COLUMN_GRANTS.GRANTEE
     *
     * @return the value of INFORMATION_SCHEMA.ROLE_COLUMN_GRANTS.GRANTEE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getGrantee() {
        return grantee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.ROLE_COLUMN_GRANTS.GRANTEE
     *
     * @param grantee the value for INFORMATION_SCHEMA.ROLE_COLUMN_GRANTS.GRANTEE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setGrantee(String grantee) {
        this.grantee = grantee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.ROLE_COLUMN_GRANTS.TABLE_CATALOG
     *
     * @return the value of INFORMATION_SCHEMA.ROLE_COLUMN_GRANTS.TABLE_CATALOG
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getTableCatalog() {
        return tableCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.ROLE_COLUMN_GRANTS.TABLE_CATALOG
     *
     * @param tableCatalog the value for INFORMATION_SCHEMA.ROLE_COLUMN_GRANTS.TABLE_CATALOG
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setTableCatalog(String tableCatalog) {
        this.tableCatalog = tableCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.ROLE_COLUMN_GRANTS.TABLE_SCHEMA
     *
     * @return the value of INFORMATION_SCHEMA.ROLE_COLUMN_GRANTS.TABLE_SCHEMA
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getTableSchema() {
        return tableSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.ROLE_COLUMN_GRANTS.TABLE_SCHEMA
     *
     * @param tableSchema the value for INFORMATION_SCHEMA.ROLE_COLUMN_GRANTS.TABLE_SCHEMA
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setTableSchema(String tableSchema) {
        this.tableSchema = tableSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.ROLE_COLUMN_GRANTS.TABLE_NAME
     *
     * @return the value of INFORMATION_SCHEMA.ROLE_COLUMN_GRANTS.TABLE_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.ROLE_COLUMN_GRANTS.TABLE_NAME
     *
     * @param tableName the value for INFORMATION_SCHEMA.ROLE_COLUMN_GRANTS.TABLE_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.ROLE_COLUMN_GRANTS.COLUMN_NAME
     *
     * @return the value of INFORMATION_SCHEMA.ROLE_COLUMN_GRANTS.COLUMN_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getColumnName() {
        return columnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.ROLE_COLUMN_GRANTS.COLUMN_NAME
     *
     * @param columnName the value for INFORMATION_SCHEMA.ROLE_COLUMN_GRANTS.COLUMN_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setColumnName(String columnName) {
        this.columnName = columnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.ROLE_COLUMN_GRANTS.PRIVILEGE_TYPE
     *
     * @return the value of INFORMATION_SCHEMA.ROLE_COLUMN_GRANTS.PRIVILEGE_TYPE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getPrivilegeType() {
        return privilegeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.ROLE_COLUMN_GRANTS.PRIVILEGE_TYPE
     *
     * @param privilegeType the value for INFORMATION_SCHEMA.ROLE_COLUMN_GRANTS.PRIVILEGE_TYPE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setPrivilegeType(String privilegeType) {
        this.privilegeType = privilegeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.ROLE_COLUMN_GRANTS.IS_GRANTABLE
     *
     * @return the value of INFORMATION_SCHEMA.ROLE_COLUMN_GRANTS.IS_GRANTABLE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getIsGrantable() {
        return isGrantable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.ROLE_COLUMN_GRANTS.IS_GRANTABLE
     *
     * @param isGrantable the value for INFORMATION_SCHEMA.ROLE_COLUMN_GRANTS.IS_GRANTABLE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setIsGrantable(String isGrantable) {
        this.isGrantable = isGrantable;
    }
}