package com.pratz.dao.table.model;

public class RoutineRoutineUsage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.ROUTINE_ROUTINE_USAGE.SPECIFIC_CATALOG
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String specificCatalog;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.ROUTINE_ROUTINE_USAGE.SPECIFIC_SCHEMA
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String specificSchema;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.ROUTINE_ROUTINE_USAGE.SPECIFIC_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String specificName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.ROUTINE_ROUTINE_USAGE.ROUTINE_CATALOG
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String routineCatalog;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.ROUTINE_ROUTINE_USAGE.ROUTINE_SCHEMA
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String routineSchema;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.ROUTINE_ROUTINE_USAGE.ROUTINE_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String routineName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.ROUTINE_ROUTINE_USAGE.SPECIFIC_CATALOG
     *
     * @return the value of INFORMATION_SCHEMA.ROUTINE_ROUTINE_USAGE.SPECIFIC_CATALOG
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getSpecificCatalog() {
        return specificCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.ROUTINE_ROUTINE_USAGE.SPECIFIC_CATALOG
     *
     * @param specificCatalog the value for INFORMATION_SCHEMA.ROUTINE_ROUTINE_USAGE.SPECIFIC_CATALOG
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setSpecificCatalog(String specificCatalog) {
        this.specificCatalog = specificCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.ROUTINE_ROUTINE_USAGE.SPECIFIC_SCHEMA
     *
     * @return the value of INFORMATION_SCHEMA.ROUTINE_ROUTINE_USAGE.SPECIFIC_SCHEMA
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getSpecificSchema() {
        return specificSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.ROUTINE_ROUTINE_USAGE.SPECIFIC_SCHEMA
     *
     * @param specificSchema the value for INFORMATION_SCHEMA.ROUTINE_ROUTINE_USAGE.SPECIFIC_SCHEMA
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setSpecificSchema(String specificSchema) {
        this.specificSchema = specificSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.ROUTINE_ROUTINE_USAGE.SPECIFIC_NAME
     *
     * @return the value of INFORMATION_SCHEMA.ROUTINE_ROUTINE_USAGE.SPECIFIC_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getSpecificName() {
        return specificName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.ROUTINE_ROUTINE_USAGE.SPECIFIC_NAME
     *
     * @param specificName the value for INFORMATION_SCHEMA.ROUTINE_ROUTINE_USAGE.SPECIFIC_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setSpecificName(String specificName) {
        this.specificName = specificName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.ROUTINE_ROUTINE_USAGE.ROUTINE_CATALOG
     *
     * @return the value of INFORMATION_SCHEMA.ROUTINE_ROUTINE_USAGE.ROUTINE_CATALOG
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getRoutineCatalog() {
        return routineCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.ROUTINE_ROUTINE_USAGE.ROUTINE_CATALOG
     *
     * @param routineCatalog the value for INFORMATION_SCHEMA.ROUTINE_ROUTINE_USAGE.ROUTINE_CATALOG
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setRoutineCatalog(String routineCatalog) {
        this.routineCatalog = routineCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.ROUTINE_ROUTINE_USAGE.ROUTINE_SCHEMA
     *
     * @return the value of INFORMATION_SCHEMA.ROUTINE_ROUTINE_USAGE.ROUTINE_SCHEMA
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getRoutineSchema() {
        return routineSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.ROUTINE_ROUTINE_USAGE.ROUTINE_SCHEMA
     *
     * @param routineSchema the value for INFORMATION_SCHEMA.ROUTINE_ROUTINE_USAGE.ROUTINE_SCHEMA
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setRoutineSchema(String routineSchema) {
        this.routineSchema = routineSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.ROUTINE_ROUTINE_USAGE.ROUTINE_NAME
     *
     * @return the value of INFORMATION_SCHEMA.ROUTINE_ROUTINE_USAGE.ROUTINE_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getRoutineName() {
        return routineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.ROUTINE_ROUTINE_USAGE.ROUTINE_NAME
     *
     * @param routineName the value for INFORMATION_SCHEMA.ROUTINE_ROUTINE_USAGE.ROUTINE_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setRoutineName(String routineName) {
        this.routineName = routineName;
    }
}