package com.pratz.dao.table.model;

public class SqlPackages {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SQL_PACKAGES.ID
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SQL_PACKAGES.NAME
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SQL_PACKAGES.IS_SUPPORTED
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    private String isSupported;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SQL_PACKAGES.IS_VERIFIED_BY
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    private String isVerifiedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SQL_PACKAGES.COMMENTS
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    private String comments;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SQL_PACKAGES.ID
     *
     * @return the value of INFORMATION_SCHEMA.SQL_PACKAGES.ID
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SQL_PACKAGES.ID
     *
     * @param id the value for INFORMATION_SCHEMA.SQL_PACKAGES.ID
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SQL_PACKAGES.NAME
     *
     * @return the value of INFORMATION_SCHEMA.SQL_PACKAGES.NAME
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SQL_PACKAGES.NAME
     *
     * @param name the value for INFORMATION_SCHEMA.SQL_PACKAGES.NAME
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SQL_PACKAGES.IS_SUPPORTED
     *
     * @return the value of INFORMATION_SCHEMA.SQL_PACKAGES.IS_SUPPORTED
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    public String getIsSupported() {
        return isSupported;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SQL_PACKAGES.IS_SUPPORTED
     *
     * @param isSupported the value for INFORMATION_SCHEMA.SQL_PACKAGES.IS_SUPPORTED
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    public void setIsSupported(String isSupported) {
        this.isSupported = isSupported;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SQL_PACKAGES.IS_VERIFIED_BY
     *
     * @return the value of INFORMATION_SCHEMA.SQL_PACKAGES.IS_VERIFIED_BY
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    public String getIsVerifiedBy() {
        return isVerifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SQL_PACKAGES.IS_VERIFIED_BY
     *
     * @param isVerifiedBy the value for INFORMATION_SCHEMA.SQL_PACKAGES.IS_VERIFIED_BY
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    public void setIsVerifiedBy(String isVerifiedBy) {
        this.isVerifiedBy = isVerifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SQL_PACKAGES.COMMENTS
     *
     * @return the value of INFORMATION_SCHEMA.SQL_PACKAGES.COMMENTS
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SQL_PACKAGES.COMMENTS
     *
     * @param comments the value for INFORMATION_SCHEMA.SQL_PACKAGES.COMMENTS
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    public void setComments(String comments) {
        this.comments = comments;
    }
}