package com.pratz.dao.table.model;

import java.util.ArrayList;
import java.util.List;

public class SystemTypeinfoCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table INFORMATION_SCHEMA.SYSTEM_TYPEINFO
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table INFORMATION_SCHEMA.SYSTEM_TYPEINFO
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table INFORMATION_SCHEMA.SYSTEM_TYPEINFO
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_TYPEINFO
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public SystemTypeinfoCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_TYPEINFO
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_TYPEINFO
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_TYPEINFO
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_TYPEINFO
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_TYPEINFO
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_TYPEINFO
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_TYPEINFO
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_TYPEINFO
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_TYPEINFO
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_TYPEINFO
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table INFORMATION_SCHEMA.SYSTEM_TYPEINFO
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTypeNameIsNull() {
            addCriterion("TYPE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andTypeNameIsNotNull() {
            addCriterion("TYPE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andTypeNameEqualTo(String value) {
            addCriterion("TYPE_NAME =", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameNotEqualTo(String value) {
            addCriterion("TYPE_NAME <>", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameGreaterThan(String value) {
            addCriterion("TYPE_NAME >", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("TYPE_NAME >=", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameLessThan(String value) {
            addCriterion("TYPE_NAME <", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameLessThanOrEqualTo(String value) {
            addCriterion("TYPE_NAME <=", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameLike(String value) {
            addCriterion("TYPE_NAME like", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameNotLike(String value) {
            addCriterion("TYPE_NAME not like", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameIn(List<String> values) {
            addCriterion("TYPE_NAME in", values, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameNotIn(List<String> values) {
            addCriterion("TYPE_NAME not in", values, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameBetween(String value1, String value2) {
            addCriterion("TYPE_NAME between", value1, value2, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameNotBetween(String value1, String value2) {
            addCriterion("TYPE_NAME not between", value1, value2, "typeName");
            return (Criteria) this;
        }

        public Criteria andDataTypeIsNull() {
            addCriterion("DATA_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andDataTypeIsNotNull() {
            addCriterion("DATA_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andDataTypeEqualTo(Short value) {
            addCriterion("DATA_TYPE =", value, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeNotEqualTo(Short value) {
            addCriterion("DATA_TYPE <>", value, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeGreaterThan(Short value) {
            addCriterion("DATA_TYPE >", value, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeGreaterThanOrEqualTo(Short value) {
            addCriterion("DATA_TYPE >=", value, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeLessThan(Short value) {
            addCriterion("DATA_TYPE <", value, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeLessThanOrEqualTo(Short value) {
            addCriterion("DATA_TYPE <=", value, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeIn(List<Short> values) {
            addCriterion("DATA_TYPE in", values, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeNotIn(List<Short> values) {
            addCriterion("DATA_TYPE not in", values, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeBetween(Short value1, Short value2) {
            addCriterion("DATA_TYPE between", value1, value2, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeNotBetween(Short value1, Short value2) {
            addCriterion("DATA_TYPE not between", value1, value2, "dataType");
            return (Criteria) this;
        }

        public Criteria andPrecisionIsNull() {
            addCriterion("PRECISION is null");
            return (Criteria) this;
        }

        public Criteria andPrecisionIsNotNull() {
            addCriterion("PRECISION is not null");
            return (Criteria) this;
        }

        public Criteria andPrecisionEqualTo(Integer value) {
            addCriterion("PRECISION =", value, "precision");
            return (Criteria) this;
        }

        public Criteria andPrecisionNotEqualTo(Integer value) {
            addCriterion("PRECISION <>", value, "precision");
            return (Criteria) this;
        }

        public Criteria andPrecisionGreaterThan(Integer value) {
            addCriterion("PRECISION >", value, "precision");
            return (Criteria) this;
        }

        public Criteria andPrecisionGreaterThanOrEqualTo(Integer value) {
            addCriterion("PRECISION >=", value, "precision");
            return (Criteria) this;
        }

        public Criteria andPrecisionLessThan(Integer value) {
            addCriterion("PRECISION <", value, "precision");
            return (Criteria) this;
        }

        public Criteria andPrecisionLessThanOrEqualTo(Integer value) {
            addCriterion("PRECISION <=", value, "precision");
            return (Criteria) this;
        }

        public Criteria andPrecisionIn(List<Integer> values) {
            addCriterion("PRECISION in", values, "precision");
            return (Criteria) this;
        }

        public Criteria andPrecisionNotIn(List<Integer> values) {
            addCriterion("PRECISION not in", values, "precision");
            return (Criteria) this;
        }

        public Criteria andPrecisionBetween(Integer value1, Integer value2) {
            addCriterion("PRECISION between", value1, value2, "precision");
            return (Criteria) this;
        }

        public Criteria andPrecisionNotBetween(Integer value1, Integer value2) {
            addCriterion("PRECISION not between", value1, value2, "precision");
            return (Criteria) this;
        }

        public Criteria andLiteralPrefixIsNull() {
            addCriterion("LITERAL_PREFIX is null");
            return (Criteria) this;
        }

        public Criteria andLiteralPrefixIsNotNull() {
            addCriterion("LITERAL_PREFIX is not null");
            return (Criteria) this;
        }

        public Criteria andLiteralPrefixEqualTo(String value) {
            addCriterion("LITERAL_PREFIX =", value, "literalPrefix");
            return (Criteria) this;
        }

        public Criteria andLiteralPrefixNotEqualTo(String value) {
            addCriterion("LITERAL_PREFIX <>", value, "literalPrefix");
            return (Criteria) this;
        }

        public Criteria andLiteralPrefixGreaterThan(String value) {
            addCriterion("LITERAL_PREFIX >", value, "literalPrefix");
            return (Criteria) this;
        }

        public Criteria andLiteralPrefixGreaterThanOrEqualTo(String value) {
            addCriterion("LITERAL_PREFIX >=", value, "literalPrefix");
            return (Criteria) this;
        }

        public Criteria andLiteralPrefixLessThan(String value) {
            addCriterion("LITERAL_PREFIX <", value, "literalPrefix");
            return (Criteria) this;
        }

        public Criteria andLiteralPrefixLessThanOrEqualTo(String value) {
            addCriterion("LITERAL_PREFIX <=", value, "literalPrefix");
            return (Criteria) this;
        }

        public Criteria andLiteralPrefixLike(String value) {
            addCriterion("LITERAL_PREFIX like", value, "literalPrefix");
            return (Criteria) this;
        }

        public Criteria andLiteralPrefixNotLike(String value) {
            addCriterion("LITERAL_PREFIX not like", value, "literalPrefix");
            return (Criteria) this;
        }

        public Criteria andLiteralPrefixIn(List<String> values) {
            addCriterion("LITERAL_PREFIX in", values, "literalPrefix");
            return (Criteria) this;
        }

        public Criteria andLiteralPrefixNotIn(List<String> values) {
            addCriterion("LITERAL_PREFIX not in", values, "literalPrefix");
            return (Criteria) this;
        }

        public Criteria andLiteralPrefixBetween(String value1, String value2) {
            addCriterion("LITERAL_PREFIX between", value1, value2, "literalPrefix");
            return (Criteria) this;
        }

        public Criteria andLiteralPrefixNotBetween(String value1, String value2) {
            addCriterion("LITERAL_PREFIX not between", value1, value2, "literalPrefix");
            return (Criteria) this;
        }

        public Criteria andLiteralSuffixIsNull() {
            addCriterion("LITERAL_SUFFIX is null");
            return (Criteria) this;
        }

        public Criteria andLiteralSuffixIsNotNull() {
            addCriterion("LITERAL_SUFFIX is not null");
            return (Criteria) this;
        }

        public Criteria andLiteralSuffixEqualTo(String value) {
            addCriterion("LITERAL_SUFFIX =", value, "literalSuffix");
            return (Criteria) this;
        }

        public Criteria andLiteralSuffixNotEqualTo(String value) {
            addCriterion("LITERAL_SUFFIX <>", value, "literalSuffix");
            return (Criteria) this;
        }

        public Criteria andLiteralSuffixGreaterThan(String value) {
            addCriterion("LITERAL_SUFFIX >", value, "literalSuffix");
            return (Criteria) this;
        }

        public Criteria andLiteralSuffixGreaterThanOrEqualTo(String value) {
            addCriterion("LITERAL_SUFFIX >=", value, "literalSuffix");
            return (Criteria) this;
        }

        public Criteria andLiteralSuffixLessThan(String value) {
            addCriterion("LITERAL_SUFFIX <", value, "literalSuffix");
            return (Criteria) this;
        }

        public Criteria andLiteralSuffixLessThanOrEqualTo(String value) {
            addCriterion("LITERAL_SUFFIX <=", value, "literalSuffix");
            return (Criteria) this;
        }

        public Criteria andLiteralSuffixLike(String value) {
            addCriterion("LITERAL_SUFFIX like", value, "literalSuffix");
            return (Criteria) this;
        }

        public Criteria andLiteralSuffixNotLike(String value) {
            addCriterion("LITERAL_SUFFIX not like", value, "literalSuffix");
            return (Criteria) this;
        }

        public Criteria andLiteralSuffixIn(List<String> values) {
            addCriterion("LITERAL_SUFFIX in", values, "literalSuffix");
            return (Criteria) this;
        }

        public Criteria andLiteralSuffixNotIn(List<String> values) {
            addCriterion("LITERAL_SUFFIX not in", values, "literalSuffix");
            return (Criteria) this;
        }

        public Criteria andLiteralSuffixBetween(String value1, String value2) {
            addCriterion("LITERAL_SUFFIX between", value1, value2, "literalSuffix");
            return (Criteria) this;
        }

        public Criteria andLiteralSuffixNotBetween(String value1, String value2) {
            addCriterion("LITERAL_SUFFIX not between", value1, value2, "literalSuffix");
            return (Criteria) this;
        }

        public Criteria andCreateParamsIsNull() {
            addCriterion("CREATE_PARAMS is null");
            return (Criteria) this;
        }

        public Criteria andCreateParamsIsNotNull() {
            addCriterion("CREATE_PARAMS is not null");
            return (Criteria) this;
        }

        public Criteria andCreateParamsEqualTo(String value) {
            addCriterion("CREATE_PARAMS =", value, "createParams");
            return (Criteria) this;
        }

        public Criteria andCreateParamsNotEqualTo(String value) {
            addCriterion("CREATE_PARAMS <>", value, "createParams");
            return (Criteria) this;
        }

        public Criteria andCreateParamsGreaterThan(String value) {
            addCriterion("CREATE_PARAMS >", value, "createParams");
            return (Criteria) this;
        }

        public Criteria andCreateParamsGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_PARAMS >=", value, "createParams");
            return (Criteria) this;
        }

        public Criteria andCreateParamsLessThan(String value) {
            addCriterion("CREATE_PARAMS <", value, "createParams");
            return (Criteria) this;
        }

        public Criteria andCreateParamsLessThanOrEqualTo(String value) {
            addCriterion("CREATE_PARAMS <=", value, "createParams");
            return (Criteria) this;
        }

        public Criteria andCreateParamsLike(String value) {
            addCriterion("CREATE_PARAMS like", value, "createParams");
            return (Criteria) this;
        }

        public Criteria andCreateParamsNotLike(String value) {
            addCriterion("CREATE_PARAMS not like", value, "createParams");
            return (Criteria) this;
        }

        public Criteria andCreateParamsIn(List<String> values) {
            addCriterion("CREATE_PARAMS in", values, "createParams");
            return (Criteria) this;
        }

        public Criteria andCreateParamsNotIn(List<String> values) {
            addCriterion("CREATE_PARAMS not in", values, "createParams");
            return (Criteria) this;
        }

        public Criteria andCreateParamsBetween(String value1, String value2) {
            addCriterion("CREATE_PARAMS between", value1, value2, "createParams");
            return (Criteria) this;
        }

        public Criteria andCreateParamsNotBetween(String value1, String value2) {
            addCriterion("CREATE_PARAMS not between", value1, value2, "createParams");
            return (Criteria) this;
        }

        public Criteria andNullableIsNull() {
            addCriterion("NULLABLE is null");
            return (Criteria) this;
        }

        public Criteria andNullableIsNotNull() {
            addCriterion("NULLABLE is not null");
            return (Criteria) this;
        }

        public Criteria andNullableEqualTo(Short value) {
            addCriterion("NULLABLE =", value, "nullable");
            return (Criteria) this;
        }

        public Criteria andNullableNotEqualTo(Short value) {
            addCriterion("NULLABLE <>", value, "nullable");
            return (Criteria) this;
        }

        public Criteria andNullableGreaterThan(Short value) {
            addCriterion("NULLABLE >", value, "nullable");
            return (Criteria) this;
        }

        public Criteria andNullableGreaterThanOrEqualTo(Short value) {
            addCriterion("NULLABLE >=", value, "nullable");
            return (Criteria) this;
        }

        public Criteria andNullableLessThan(Short value) {
            addCriterion("NULLABLE <", value, "nullable");
            return (Criteria) this;
        }

        public Criteria andNullableLessThanOrEqualTo(Short value) {
            addCriterion("NULLABLE <=", value, "nullable");
            return (Criteria) this;
        }

        public Criteria andNullableIn(List<Short> values) {
            addCriterion("NULLABLE in", values, "nullable");
            return (Criteria) this;
        }

        public Criteria andNullableNotIn(List<Short> values) {
            addCriterion("NULLABLE not in", values, "nullable");
            return (Criteria) this;
        }

        public Criteria andNullableBetween(Short value1, Short value2) {
            addCriterion("NULLABLE between", value1, value2, "nullable");
            return (Criteria) this;
        }

        public Criteria andNullableNotBetween(Short value1, Short value2) {
            addCriterion("NULLABLE not between", value1, value2, "nullable");
            return (Criteria) this;
        }

        public Criteria andCaseSensitiveIsNull() {
            addCriterion("CASE_SENSITIVE is null");
            return (Criteria) this;
        }

        public Criteria andCaseSensitiveIsNotNull() {
            addCriterion("CASE_SENSITIVE is not null");
            return (Criteria) this;
        }

        public Criteria andCaseSensitiveEqualTo(Boolean value) {
            addCriterion("CASE_SENSITIVE =", value, "caseSensitive");
            return (Criteria) this;
        }

        public Criteria andCaseSensitiveNotEqualTo(Boolean value) {
            addCriterion("CASE_SENSITIVE <>", value, "caseSensitive");
            return (Criteria) this;
        }

        public Criteria andCaseSensitiveGreaterThan(Boolean value) {
            addCriterion("CASE_SENSITIVE >", value, "caseSensitive");
            return (Criteria) this;
        }

        public Criteria andCaseSensitiveGreaterThanOrEqualTo(Boolean value) {
            addCriterion("CASE_SENSITIVE >=", value, "caseSensitive");
            return (Criteria) this;
        }

        public Criteria andCaseSensitiveLessThan(Boolean value) {
            addCriterion("CASE_SENSITIVE <", value, "caseSensitive");
            return (Criteria) this;
        }

        public Criteria andCaseSensitiveLessThanOrEqualTo(Boolean value) {
            addCriterion("CASE_SENSITIVE <=", value, "caseSensitive");
            return (Criteria) this;
        }

        public Criteria andCaseSensitiveIn(List<Boolean> values) {
            addCriterion("CASE_SENSITIVE in", values, "caseSensitive");
            return (Criteria) this;
        }

        public Criteria andCaseSensitiveNotIn(List<Boolean> values) {
            addCriterion("CASE_SENSITIVE not in", values, "caseSensitive");
            return (Criteria) this;
        }

        public Criteria andCaseSensitiveBetween(Boolean value1, Boolean value2) {
            addCriterion("CASE_SENSITIVE between", value1, value2, "caseSensitive");
            return (Criteria) this;
        }

        public Criteria andCaseSensitiveNotBetween(Boolean value1, Boolean value2) {
            addCriterion("CASE_SENSITIVE not between", value1, value2, "caseSensitive");
            return (Criteria) this;
        }

        public Criteria andSearchableIsNull() {
            addCriterion("SEARCHABLE is null");
            return (Criteria) this;
        }

        public Criteria andSearchableIsNotNull() {
            addCriterion("SEARCHABLE is not null");
            return (Criteria) this;
        }

        public Criteria andSearchableEqualTo(Integer value) {
            addCriterion("SEARCHABLE =", value, "searchable");
            return (Criteria) this;
        }

        public Criteria andSearchableNotEqualTo(Integer value) {
            addCriterion("SEARCHABLE <>", value, "searchable");
            return (Criteria) this;
        }

        public Criteria andSearchableGreaterThan(Integer value) {
            addCriterion("SEARCHABLE >", value, "searchable");
            return (Criteria) this;
        }

        public Criteria andSearchableGreaterThanOrEqualTo(Integer value) {
            addCriterion("SEARCHABLE >=", value, "searchable");
            return (Criteria) this;
        }

        public Criteria andSearchableLessThan(Integer value) {
            addCriterion("SEARCHABLE <", value, "searchable");
            return (Criteria) this;
        }

        public Criteria andSearchableLessThanOrEqualTo(Integer value) {
            addCriterion("SEARCHABLE <=", value, "searchable");
            return (Criteria) this;
        }

        public Criteria andSearchableIn(List<Integer> values) {
            addCriterion("SEARCHABLE in", values, "searchable");
            return (Criteria) this;
        }

        public Criteria andSearchableNotIn(List<Integer> values) {
            addCriterion("SEARCHABLE not in", values, "searchable");
            return (Criteria) this;
        }

        public Criteria andSearchableBetween(Integer value1, Integer value2) {
            addCriterion("SEARCHABLE between", value1, value2, "searchable");
            return (Criteria) this;
        }

        public Criteria andSearchableNotBetween(Integer value1, Integer value2) {
            addCriterion("SEARCHABLE not between", value1, value2, "searchable");
            return (Criteria) this;
        }

        public Criteria andUnsignedAttributeIsNull() {
            addCriterion("UNSIGNED_ATTRIBUTE is null");
            return (Criteria) this;
        }

        public Criteria andUnsignedAttributeIsNotNull() {
            addCriterion("UNSIGNED_ATTRIBUTE is not null");
            return (Criteria) this;
        }

        public Criteria andUnsignedAttributeEqualTo(Boolean value) {
            addCriterion("UNSIGNED_ATTRIBUTE =", value, "unsignedAttribute");
            return (Criteria) this;
        }

        public Criteria andUnsignedAttributeNotEqualTo(Boolean value) {
            addCriterion("UNSIGNED_ATTRIBUTE <>", value, "unsignedAttribute");
            return (Criteria) this;
        }

        public Criteria andUnsignedAttributeGreaterThan(Boolean value) {
            addCriterion("UNSIGNED_ATTRIBUTE >", value, "unsignedAttribute");
            return (Criteria) this;
        }

        public Criteria andUnsignedAttributeGreaterThanOrEqualTo(Boolean value) {
            addCriterion("UNSIGNED_ATTRIBUTE >=", value, "unsignedAttribute");
            return (Criteria) this;
        }

        public Criteria andUnsignedAttributeLessThan(Boolean value) {
            addCriterion("UNSIGNED_ATTRIBUTE <", value, "unsignedAttribute");
            return (Criteria) this;
        }

        public Criteria andUnsignedAttributeLessThanOrEqualTo(Boolean value) {
            addCriterion("UNSIGNED_ATTRIBUTE <=", value, "unsignedAttribute");
            return (Criteria) this;
        }

        public Criteria andUnsignedAttributeIn(List<Boolean> values) {
            addCriterion("UNSIGNED_ATTRIBUTE in", values, "unsignedAttribute");
            return (Criteria) this;
        }

        public Criteria andUnsignedAttributeNotIn(List<Boolean> values) {
            addCriterion("UNSIGNED_ATTRIBUTE not in", values, "unsignedAttribute");
            return (Criteria) this;
        }

        public Criteria andUnsignedAttributeBetween(Boolean value1, Boolean value2) {
            addCriterion("UNSIGNED_ATTRIBUTE between", value1, value2, "unsignedAttribute");
            return (Criteria) this;
        }

        public Criteria andUnsignedAttributeNotBetween(Boolean value1, Boolean value2) {
            addCriterion("UNSIGNED_ATTRIBUTE not between", value1, value2, "unsignedAttribute");
            return (Criteria) this;
        }

        public Criteria andFixedPrecScaleIsNull() {
            addCriterion("FIXED_PREC_SCALE is null");
            return (Criteria) this;
        }

        public Criteria andFixedPrecScaleIsNotNull() {
            addCriterion("FIXED_PREC_SCALE is not null");
            return (Criteria) this;
        }

        public Criteria andFixedPrecScaleEqualTo(Boolean value) {
            addCriterion("FIXED_PREC_SCALE =", value, "fixedPrecScale");
            return (Criteria) this;
        }

        public Criteria andFixedPrecScaleNotEqualTo(Boolean value) {
            addCriterion("FIXED_PREC_SCALE <>", value, "fixedPrecScale");
            return (Criteria) this;
        }

        public Criteria andFixedPrecScaleGreaterThan(Boolean value) {
            addCriterion("FIXED_PREC_SCALE >", value, "fixedPrecScale");
            return (Criteria) this;
        }

        public Criteria andFixedPrecScaleGreaterThanOrEqualTo(Boolean value) {
            addCriterion("FIXED_PREC_SCALE >=", value, "fixedPrecScale");
            return (Criteria) this;
        }

        public Criteria andFixedPrecScaleLessThan(Boolean value) {
            addCriterion("FIXED_PREC_SCALE <", value, "fixedPrecScale");
            return (Criteria) this;
        }

        public Criteria andFixedPrecScaleLessThanOrEqualTo(Boolean value) {
            addCriterion("FIXED_PREC_SCALE <=", value, "fixedPrecScale");
            return (Criteria) this;
        }

        public Criteria andFixedPrecScaleIn(List<Boolean> values) {
            addCriterion("FIXED_PREC_SCALE in", values, "fixedPrecScale");
            return (Criteria) this;
        }

        public Criteria andFixedPrecScaleNotIn(List<Boolean> values) {
            addCriterion("FIXED_PREC_SCALE not in", values, "fixedPrecScale");
            return (Criteria) this;
        }

        public Criteria andFixedPrecScaleBetween(Boolean value1, Boolean value2) {
            addCriterion("FIXED_PREC_SCALE between", value1, value2, "fixedPrecScale");
            return (Criteria) this;
        }

        public Criteria andFixedPrecScaleNotBetween(Boolean value1, Boolean value2) {
            addCriterion("FIXED_PREC_SCALE not between", value1, value2, "fixedPrecScale");
            return (Criteria) this;
        }

        public Criteria andAutoIncrementIsNull() {
            addCriterion("AUTO_INCREMENT is null");
            return (Criteria) this;
        }

        public Criteria andAutoIncrementIsNotNull() {
            addCriterion("AUTO_INCREMENT is not null");
            return (Criteria) this;
        }

        public Criteria andAutoIncrementEqualTo(Boolean value) {
            addCriterion("AUTO_INCREMENT =", value, "autoIncrement");
            return (Criteria) this;
        }

        public Criteria andAutoIncrementNotEqualTo(Boolean value) {
            addCriterion("AUTO_INCREMENT <>", value, "autoIncrement");
            return (Criteria) this;
        }

        public Criteria andAutoIncrementGreaterThan(Boolean value) {
            addCriterion("AUTO_INCREMENT >", value, "autoIncrement");
            return (Criteria) this;
        }

        public Criteria andAutoIncrementGreaterThanOrEqualTo(Boolean value) {
            addCriterion("AUTO_INCREMENT >=", value, "autoIncrement");
            return (Criteria) this;
        }

        public Criteria andAutoIncrementLessThan(Boolean value) {
            addCriterion("AUTO_INCREMENT <", value, "autoIncrement");
            return (Criteria) this;
        }

        public Criteria andAutoIncrementLessThanOrEqualTo(Boolean value) {
            addCriterion("AUTO_INCREMENT <=", value, "autoIncrement");
            return (Criteria) this;
        }

        public Criteria andAutoIncrementIn(List<Boolean> values) {
            addCriterion("AUTO_INCREMENT in", values, "autoIncrement");
            return (Criteria) this;
        }

        public Criteria andAutoIncrementNotIn(List<Boolean> values) {
            addCriterion("AUTO_INCREMENT not in", values, "autoIncrement");
            return (Criteria) this;
        }

        public Criteria andAutoIncrementBetween(Boolean value1, Boolean value2) {
            addCriterion("AUTO_INCREMENT between", value1, value2, "autoIncrement");
            return (Criteria) this;
        }

        public Criteria andAutoIncrementNotBetween(Boolean value1, Boolean value2) {
            addCriterion("AUTO_INCREMENT not between", value1, value2, "autoIncrement");
            return (Criteria) this;
        }

        public Criteria andLocalTypeNameIsNull() {
            addCriterion("LOCAL_TYPE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andLocalTypeNameIsNotNull() {
            addCriterion("LOCAL_TYPE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andLocalTypeNameEqualTo(String value) {
            addCriterion("LOCAL_TYPE_NAME =", value, "localTypeName");
            return (Criteria) this;
        }

        public Criteria andLocalTypeNameNotEqualTo(String value) {
            addCriterion("LOCAL_TYPE_NAME <>", value, "localTypeName");
            return (Criteria) this;
        }

        public Criteria andLocalTypeNameGreaterThan(String value) {
            addCriterion("LOCAL_TYPE_NAME >", value, "localTypeName");
            return (Criteria) this;
        }

        public Criteria andLocalTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("LOCAL_TYPE_NAME >=", value, "localTypeName");
            return (Criteria) this;
        }

        public Criteria andLocalTypeNameLessThan(String value) {
            addCriterion("LOCAL_TYPE_NAME <", value, "localTypeName");
            return (Criteria) this;
        }

        public Criteria andLocalTypeNameLessThanOrEqualTo(String value) {
            addCriterion("LOCAL_TYPE_NAME <=", value, "localTypeName");
            return (Criteria) this;
        }

        public Criteria andLocalTypeNameLike(String value) {
            addCriterion("LOCAL_TYPE_NAME like", value, "localTypeName");
            return (Criteria) this;
        }

        public Criteria andLocalTypeNameNotLike(String value) {
            addCriterion("LOCAL_TYPE_NAME not like", value, "localTypeName");
            return (Criteria) this;
        }

        public Criteria andLocalTypeNameIn(List<String> values) {
            addCriterion("LOCAL_TYPE_NAME in", values, "localTypeName");
            return (Criteria) this;
        }

        public Criteria andLocalTypeNameNotIn(List<String> values) {
            addCriterion("LOCAL_TYPE_NAME not in", values, "localTypeName");
            return (Criteria) this;
        }

        public Criteria andLocalTypeNameBetween(String value1, String value2) {
            addCriterion("LOCAL_TYPE_NAME between", value1, value2, "localTypeName");
            return (Criteria) this;
        }

        public Criteria andLocalTypeNameNotBetween(String value1, String value2) {
            addCriterion("LOCAL_TYPE_NAME not between", value1, value2, "localTypeName");
            return (Criteria) this;
        }

        public Criteria andMinimumScaleIsNull() {
            addCriterion("MINIMUM_SCALE is null");
            return (Criteria) this;
        }

        public Criteria andMinimumScaleIsNotNull() {
            addCriterion("MINIMUM_SCALE is not null");
            return (Criteria) this;
        }

        public Criteria andMinimumScaleEqualTo(Short value) {
            addCriterion("MINIMUM_SCALE =", value, "minimumScale");
            return (Criteria) this;
        }

        public Criteria andMinimumScaleNotEqualTo(Short value) {
            addCriterion("MINIMUM_SCALE <>", value, "minimumScale");
            return (Criteria) this;
        }

        public Criteria andMinimumScaleGreaterThan(Short value) {
            addCriterion("MINIMUM_SCALE >", value, "minimumScale");
            return (Criteria) this;
        }

        public Criteria andMinimumScaleGreaterThanOrEqualTo(Short value) {
            addCriterion("MINIMUM_SCALE >=", value, "minimumScale");
            return (Criteria) this;
        }

        public Criteria andMinimumScaleLessThan(Short value) {
            addCriterion("MINIMUM_SCALE <", value, "minimumScale");
            return (Criteria) this;
        }

        public Criteria andMinimumScaleLessThanOrEqualTo(Short value) {
            addCriterion("MINIMUM_SCALE <=", value, "minimumScale");
            return (Criteria) this;
        }

        public Criteria andMinimumScaleIn(List<Short> values) {
            addCriterion("MINIMUM_SCALE in", values, "minimumScale");
            return (Criteria) this;
        }

        public Criteria andMinimumScaleNotIn(List<Short> values) {
            addCriterion("MINIMUM_SCALE not in", values, "minimumScale");
            return (Criteria) this;
        }

        public Criteria andMinimumScaleBetween(Short value1, Short value2) {
            addCriterion("MINIMUM_SCALE between", value1, value2, "minimumScale");
            return (Criteria) this;
        }

        public Criteria andMinimumScaleNotBetween(Short value1, Short value2) {
            addCriterion("MINIMUM_SCALE not between", value1, value2, "minimumScale");
            return (Criteria) this;
        }

        public Criteria andMaximumScaleIsNull() {
            addCriterion("MAXIMUM_SCALE is null");
            return (Criteria) this;
        }

        public Criteria andMaximumScaleIsNotNull() {
            addCriterion("MAXIMUM_SCALE is not null");
            return (Criteria) this;
        }

        public Criteria andMaximumScaleEqualTo(Short value) {
            addCriterion("MAXIMUM_SCALE =", value, "maximumScale");
            return (Criteria) this;
        }

        public Criteria andMaximumScaleNotEqualTo(Short value) {
            addCriterion("MAXIMUM_SCALE <>", value, "maximumScale");
            return (Criteria) this;
        }

        public Criteria andMaximumScaleGreaterThan(Short value) {
            addCriterion("MAXIMUM_SCALE >", value, "maximumScale");
            return (Criteria) this;
        }

        public Criteria andMaximumScaleGreaterThanOrEqualTo(Short value) {
            addCriterion("MAXIMUM_SCALE >=", value, "maximumScale");
            return (Criteria) this;
        }

        public Criteria andMaximumScaleLessThan(Short value) {
            addCriterion("MAXIMUM_SCALE <", value, "maximumScale");
            return (Criteria) this;
        }

        public Criteria andMaximumScaleLessThanOrEqualTo(Short value) {
            addCriterion("MAXIMUM_SCALE <=", value, "maximumScale");
            return (Criteria) this;
        }

        public Criteria andMaximumScaleIn(List<Short> values) {
            addCriterion("MAXIMUM_SCALE in", values, "maximumScale");
            return (Criteria) this;
        }

        public Criteria andMaximumScaleNotIn(List<Short> values) {
            addCriterion("MAXIMUM_SCALE not in", values, "maximumScale");
            return (Criteria) this;
        }

        public Criteria andMaximumScaleBetween(Short value1, Short value2) {
            addCriterion("MAXIMUM_SCALE between", value1, value2, "maximumScale");
            return (Criteria) this;
        }

        public Criteria andMaximumScaleNotBetween(Short value1, Short value2) {
            addCriterion("MAXIMUM_SCALE not between", value1, value2, "maximumScale");
            return (Criteria) this;
        }

        public Criteria andSqlDataTypeIsNull() {
            addCriterion("SQL_DATA_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andSqlDataTypeIsNotNull() {
            addCriterion("SQL_DATA_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andSqlDataTypeEqualTo(Integer value) {
            addCriterion("SQL_DATA_TYPE =", value, "sqlDataType");
            return (Criteria) this;
        }

        public Criteria andSqlDataTypeNotEqualTo(Integer value) {
            addCriterion("SQL_DATA_TYPE <>", value, "sqlDataType");
            return (Criteria) this;
        }

        public Criteria andSqlDataTypeGreaterThan(Integer value) {
            addCriterion("SQL_DATA_TYPE >", value, "sqlDataType");
            return (Criteria) this;
        }

        public Criteria andSqlDataTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("SQL_DATA_TYPE >=", value, "sqlDataType");
            return (Criteria) this;
        }

        public Criteria andSqlDataTypeLessThan(Integer value) {
            addCriterion("SQL_DATA_TYPE <", value, "sqlDataType");
            return (Criteria) this;
        }

        public Criteria andSqlDataTypeLessThanOrEqualTo(Integer value) {
            addCriterion("SQL_DATA_TYPE <=", value, "sqlDataType");
            return (Criteria) this;
        }

        public Criteria andSqlDataTypeIn(List<Integer> values) {
            addCriterion("SQL_DATA_TYPE in", values, "sqlDataType");
            return (Criteria) this;
        }

        public Criteria andSqlDataTypeNotIn(List<Integer> values) {
            addCriterion("SQL_DATA_TYPE not in", values, "sqlDataType");
            return (Criteria) this;
        }

        public Criteria andSqlDataTypeBetween(Integer value1, Integer value2) {
            addCriterion("SQL_DATA_TYPE between", value1, value2, "sqlDataType");
            return (Criteria) this;
        }

        public Criteria andSqlDataTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("SQL_DATA_TYPE not between", value1, value2, "sqlDataType");
            return (Criteria) this;
        }

        public Criteria andSqlDatetimeSubIsNull() {
            addCriterion("SQL_DATETIME_SUB is null");
            return (Criteria) this;
        }

        public Criteria andSqlDatetimeSubIsNotNull() {
            addCriterion("SQL_DATETIME_SUB is not null");
            return (Criteria) this;
        }

        public Criteria andSqlDatetimeSubEqualTo(Integer value) {
            addCriterion("SQL_DATETIME_SUB =", value, "sqlDatetimeSub");
            return (Criteria) this;
        }

        public Criteria andSqlDatetimeSubNotEqualTo(Integer value) {
            addCriterion("SQL_DATETIME_SUB <>", value, "sqlDatetimeSub");
            return (Criteria) this;
        }

        public Criteria andSqlDatetimeSubGreaterThan(Integer value) {
            addCriterion("SQL_DATETIME_SUB >", value, "sqlDatetimeSub");
            return (Criteria) this;
        }

        public Criteria andSqlDatetimeSubGreaterThanOrEqualTo(Integer value) {
            addCriterion("SQL_DATETIME_SUB >=", value, "sqlDatetimeSub");
            return (Criteria) this;
        }

        public Criteria andSqlDatetimeSubLessThan(Integer value) {
            addCriterion("SQL_DATETIME_SUB <", value, "sqlDatetimeSub");
            return (Criteria) this;
        }

        public Criteria andSqlDatetimeSubLessThanOrEqualTo(Integer value) {
            addCriterion("SQL_DATETIME_SUB <=", value, "sqlDatetimeSub");
            return (Criteria) this;
        }

        public Criteria andSqlDatetimeSubIn(List<Integer> values) {
            addCriterion("SQL_DATETIME_SUB in", values, "sqlDatetimeSub");
            return (Criteria) this;
        }

        public Criteria andSqlDatetimeSubNotIn(List<Integer> values) {
            addCriterion("SQL_DATETIME_SUB not in", values, "sqlDatetimeSub");
            return (Criteria) this;
        }

        public Criteria andSqlDatetimeSubBetween(Integer value1, Integer value2) {
            addCriterion("SQL_DATETIME_SUB between", value1, value2, "sqlDatetimeSub");
            return (Criteria) this;
        }

        public Criteria andSqlDatetimeSubNotBetween(Integer value1, Integer value2) {
            addCriterion("SQL_DATETIME_SUB not between", value1, value2, "sqlDatetimeSub");
            return (Criteria) this;
        }

        public Criteria andNumPrecRadixIsNull() {
            addCriterion("NUM_PREC_RADIX is null");
            return (Criteria) this;
        }

        public Criteria andNumPrecRadixIsNotNull() {
            addCriterion("NUM_PREC_RADIX is not null");
            return (Criteria) this;
        }

        public Criteria andNumPrecRadixEqualTo(Integer value) {
            addCriterion("NUM_PREC_RADIX =", value, "numPrecRadix");
            return (Criteria) this;
        }

        public Criteria andNumPrecRadixNotEqualTo(Integer value) {
            addCriterion("NUM_PREC_RADIX <>", value, "numPrecRadix");
            return (Criteria) this;
        }

        public Criteria andNumPrecRadixGreaterThan(Integer value) {
            addCriterion("NUM_PREC_RADIX >", value, "numPrecRadix");
            return (Criteria) this;
        }

        public Criteria andNumPrecRadixGreaterThanOrEqualTo(Integer value) {
            addCriterion("NUM_PREC_RADIX >=", value, "numPrecRadix");
            return (Criteria) this;
        }

        public Criteria andNumPrecRadixLessThan(Integer value) {
            addCriterion("NUM_PREC_RADIX <", value, "numPrecRadix");
            return (Criteria) this;
        }

        public Criteria andNumPrecRadixLessThanOrEqualTo(Integer value) {
            addCriterion("NUM_PREC_RADIX <=", value, "numPrecRadix");
            return (Criteria) this;
        }

        public Criteria andNumPrecRadixIn(List<Integer> values) {
            addCriterion("NUM_PREC_RADIX in", values, "numPrecRadix");
            return (Criteria) this;
        }

        public Criteria andNumPrecRadixNotIn(List<Integer> values) {
            addCriterion("NUM_PREC_RADIX not in", values, "numPrecRadix");
            return (Criteria) this;
        }

        public Criteria andNumPrecRadixBetween(Integer value1, Integer value2) {
            addCriterion("NUM_PREC_RADIX between", value1, value2, "numPrecRadix");
            return (Criteria) this;
        }

        public Criteria andNumPrecRadixNotBetween(Integer value1, Integer value2) {
            addCriterion("NUM_PREC_RADIX not between", value1, value2, "numPrecRadix");
            return (Criteria) this;
        }

        public Criteria andIntervalPrecisionIsNull() {
            addCriterion("INTERVAL_PRECISION is null");
            return (Criteria) this;
        }

        public Criteria andIntervalPrecisionIsNotNull() {
            addCriterion("INTERVAL_PRECISION is not null");
            return (Criteria) this;
        }

        public Criteria andIntervalPrecisionEqualTo(Integer value) {
            addCriterion("INTERVAL_PRECISION =", value, "intervalPrecision");
            return (Criteria) this;
        }

        public Criteria andIntervalPrecisionNotEqualTo(Integer value) {
            addCriterion("INTERVAL_PRECISION <>", value, "intervalPrecision");
            return (Criteria) this;
        }

        public Criteria andIntervalPrecisionGreaterThan(Integer value) {
            addCriterion("INTERVAL_PRECISION >", value, "intervalPrecision");
            return (Criteria) this;
        }

        public Criteria andIntervalPrecisionGreaterThanOrEqualTo(Integer value) {
            addCriterion("INTERVAL_PRECISION >=", value, "intervalPrecision");
            return (Criteria) this;
        }

        public Criteria andIntervalPrecisionLessThan(Integer value) {
            addCriterion("INTERVAL_PRECISION <", value, "intervalPrecision");
            return (Criteria) this;
        }

        public Criteria andIntervalPrecisionLessThanOrEqualTo(Integer value) {
            addCriterion("INTERVAL_PRECISION <=", value, "intervalPrecision");
            return (Criteria) this;
        }

        public Criteria andIntervalPrecisionIn(List<Integer> values) {
            addCriterion("INTERVAL_PRECISION in", values, "intervalPrecision");
            return (Criteria) this;
        }

        public Criteria andIntervalPrecisionNotIn(List<Integer> values) {
            addCriterion("INTERVAL_PRECISION not in", values, "intervalPrecision");
            return (Criteria) this;
        }

        public Criteria andIntervalPrecisionBetween(Integer value1, Integer value2) {
            addCriterion("INTERVAL_PRECISION between", value1, value2, "intervalPrecision");
            return (Criteria) this;
        }

        public Criteria andIntervalPrecisionNotBetween(Integer value1, Integer value2) {
            addCriterion("INTERVAL_PRECISION not between", value1, value2, "intervalPrecision");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table INFORMATION_SCHEMA.SYSTEM_TYPEINFO
     *
     * @mbggenerated do_not_delete_during_merge Sat Mar 21 14:24:50 ICT 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table INFORMATION_SCHEMA.SYSTEM_TYPEINFO
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}