package com.pratz.dao.table.model;

public class SystemTexttables {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.TABLE_CAT
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String tableCat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.TABLE_SCHEM
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String tableSchem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.TABLE_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String tableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.DATA_SOURCE_DEFINTION
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String dataSourceDefintion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.FILE_PATH
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String filePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.FILE_ENCODING
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String fileEncoding;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.FIELD_SEPARATOR
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String fieldSeparator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.VARCHAR_SEPARATOR
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String varcharSeparator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.LONGVARCHAR_SEPARATOR
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String longvarcharSeparator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.IS_IGNORE_FIRST
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private Boolean isIgnoreFirst;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.IS_ALL_QUOTED
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private Boolean isAllQuoted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.IS_QUOTED
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private Boolean isQuoted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.IS_DESC
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private Boolean isDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.TABLE_CAT
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.TABLE_CAT
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getTableCat() {
        return tableCat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.TABLE_CAT
     *
     * @param tableCat the value for INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.TABLE_CAT
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setTableCat(String tableCat) {
        this.tableCat = tableCat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.TABLE_SCHEM
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.TABLE_SCHEM
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getTableSchem() {
        return tableSchem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.TABLE_SCHEM
     *
     * @param tableSchem the value for INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.TABLE_SCHEM
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setTableSchem(String tableSchem) {
        this.tableSchem = tableSchem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.TABLE_NAME
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.TABLE_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.TABLE_NAME
     *
     * @param tableName the value for INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.TABLE_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.DATA_SOURCE_DEFINTION
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.DATA_SOURCE_DEFINTION
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getDataSourceDefintion() {
        return dataSourceDefintion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.DATA_SOURCE_DEFINTION
     *
     * @param dataSourceDefintion the value for INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.DATA_SOURCE_DEFINTION
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setDataSourceDefintion(String dataSourceDefintion) {
        this.dataSourceDefintion = dataSourceDefintion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.FILE_PATH
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.FILE_PATH
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.FILE_PATH
     *
     * @param filePath the value for INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.FILE_PATH
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.FILE_ENCODING
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.FILE_ENCODING
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getFileEncoding() {
        return fileEncoding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.FILE_ENCODING
     *
     * @param fileEncoding the value for INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.FILE_ENCODING
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setFileEncoding(String fileEncoding) {
        this.fileEncoding = fileEncoding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.FIELD_SEPARATOR
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.FIELD_SEPARATOR
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getFieldSeparator() {
        return fieldSeparator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.FIELD_SEPARATOR
     *
     * @param fieldSeparator the value for INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.FIELD_SEPARATOR
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setFieldSeparator(String fieldSeparator) {
        this.fieldSeparator = fieldSeparator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.VARCHAR_SEPARATOR
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.VARCHAR_SEPARATOR
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getVarcharSeparator() {
        return varcharSeparator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.VARCHAR_SEPARATOR
     *
     * @param varcharSeparator the value for INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.VARCHAR_SEPARATOR
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setVarcharSeparator(String varcharSeparator) {
        this.varcharSeparator = varcharSeparator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.LONGVARCHAR_SEPARATOR
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.LONGVARCHAR_SEPARATOR
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getLongvarcharSeparator() {
        return longvarcharSeparator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.LONGVARCHAR_SEPARATOR
     *
     * @param longvarcharSeparator the value for INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.LONGVARCHAR_SEPARATOR
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setLongvarcharSeparator(String longvarcharSeparator) {
        this.longvarcharSeparator = longvarcharSeparator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.IS_IGNORE_FIRST
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.IS_IGNORE_FIRST
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public Boolean getIsIgnoreFirst() {
        return isIgnoreFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.IS_IGNORE_FIRST
     *
     * @param isIgnoreFirst the value for INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.IS_IGNORE_FIRST
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setIsIgnoreFirst(Boolean isIgnoreFirst) {
        this.isIgnoreFirst = isIgnoreFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.IS_ALL_QUOTED
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.IS_ALL_QUOTED
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public Boolean getIsAllQuoted() {
        return isAllQuoted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.IS_ALL_QUOTED
     *
     * @param isAllQuoted the value for INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.IS_ALL_QUOTED
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setIsAllQuoted(Boolean isAllQuoted) {
        this.isAllQuoted = isAllQuoted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.IS_QUOTED
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.IS_QUOTED
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public Boolean getIsQuoted() {
        return isQuoted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.IS_QUOTED
     *
     * @param isQuoted the value for INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.IS_QUOTED
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setIsQuoted(Boolean isQuoted) {
        this.isQuoted = isQuoted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.IS_DESC
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.IS_DESC
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public Boolean getIsDesc() {
        return isDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.IS_DESC
     *
     * @param isDesc the value for INFORMATION_SCHEMA.SYSTEM_TEXTTABLES.IS_DESC
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setIsDesc(Boolean isDesc) {
        this.isDesc = isDesc;
    }
}