package com.pratz.dao.table.model;

import java.util.ArrayList;
import java.util.List;

public class SystemTexttablesCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table INFORMATION_SCHEMA.SYSTEM_TEXTTABLES
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table INFORMATION_SCHEMA.SYSTEM_TEXTTABLES
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table INFORMATION_SCHEMA.SYSTEM_TEXTTABLES
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_TEXTTABLES
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public SystemTexttablesCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_TEXTTABLES
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_TEXTTABLES
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_TEXTTABLES
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_TEXTTABLES
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_TEXTTABLES
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_TEXTTABLES
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_TEXTTABLES
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_TEXTTABLES
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_TEXTTABLES
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.SYSTEM_TEXTTABLES
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table INFORMATION_SCHEMA.SYSTEM_TEXTTABLES
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTableCatIsNull() {
            addCriterion("TABLE_CAT is null");
            return (Criteria) this;
        }

        public Criteria andTableCatIsNotNull() {
            addCriterion("TABLE_CAT is not null");
            return (Criteria) this;
        }

        public Criteria andTableCatEqualTo(String value) {
            addCriterion("TABLE_CAT =", value, "tableCat");
            return (Criteria) this;
        }

        public Criteria andTableCatNotEqualTo(String value) {
            addCriterion("TABLE_CAT <>", value, "tableCat");
            return (Criteria) this;
        }

        public Criteria andTableCatGreaterThan(String value) {
            addCriterion("TABLE_CAT >", value, "tableCat");
            return (Criteria) this;
        }

        public Criteria andTableCatGreaterThanOrEqualTo(String value) {
            addCriterion("TABLE_CAT >=", value, "tableCat");
            return (Criteria) this;
        }

        public Criteria andTableCatLessThan(String value) {
            addCriterion("TABLE_CAT <", value, "tableCat");
            return (Criteria) this;
        }

        public Criteria andTableCatLessThanOrEqualTo(String value) {
            addCriterion("TABLE_CAT <=", value, "tableCat");
            return (Criteria) this;
        }

        public Criteria andTableCatLike(String value) {
            addCriterion("TABLE_CAT like", value, "tableCat");
            return (Criteria) this;
        }

        public Criteria andTableCatNotLike(String value) {
            addCriterion("TABLE_CAT not like", value, "tableCat");
            return (Criteria) this;
        }

        public Criteria andTableCatIn(List<String> values) {
            addCriterion("TABLE_CAT in", values, "tableCat");
            return (Criteria) this;
        }

        public Criteria andTableCatNotIn(List<String> values) {
            addCriterion("TABLE_CAT not in", values, "tableCat");
            return (Criteria) this;
        }

        public Criteria andTableCatBetween(String value1, String value2) {
            addCriterion("TABLE_CAT between", value1, value2, "tableCat");
            return (Criteria) this;
        }

        public Criteria andTableCatNotBetween(String value1, String value2) {
            addCriterion("TABLE_CAT not between", value1, value2, "tableCat");
            return (Criteria) this;
        }

        public Criteria andTableSchemIsNull() {
            addCriterion("TABLE_SCHEM is null");
            return (Criteria) this;
        }

        public Criteria andTableSchemIsNotNull() {
            addCriterion("TABLE_SCHEM is not null");
            return (Criteria) this;
        }

        public Criteria andTableSchemEqualTo(String value) {
            addCriterion("TABLE_SCHEM =", value, "tableSchem");
            return (Criteria) this;
        }

        public Criteria andTableSchemNotEqualTo(String value) {
            addCriterion("TABLE_SCHEM <>", value, "tableSchem");
            return (Criteria) this;
        }

        public Criteria andTableSchemGreaterThan(String value) {
            addCriterion("TABLE_SCHEM >", value, "tableSchem");
            return (Criteria) this;
        }

        public Criteria andTableSchemGreaterThanOrEqualTo(String value) {
            addCriterion("TABLE_SCHEM >=", value, "tableSchem");
            return (Criteria) this;
        }

        public Criteria andTableSchemLessThan(String value) {
            addCriterion("TABLE_SCHEM <", value, "tableSchem");
            return (Criteria) this;
        }

        public Criteria andTableSchemLessThanOrEqualTo(String value) {
            addCriterion("TABLE_SCHEM <=", value, "tableSchem");
            return (Criteria) this;
        }

        public Criteria andTableSchemLike(String value) {
            addCriterion("TABLE_SCHEM like", value, "tableSchem");
            return (Criteria) this;
        }

        public Criteria andTableSchemNotLike(String value) {
            addCriterion("TABLE_SCHEM not like", value, "tableSchem");
            return (Criteria) this;
        }

        public Criteria andTableSchemIn(List<String> values) {
            addCriterion("TABLE_SCHEM in", values, "tableSchem");
            return (Criteria) this;
        }

        public Criteria andTableSchemNotIn(List<String> values) {
            addCriterion("TABLE_SCHEM not in", values, "tableSchem");
            return (Criteria) this;
        }

        public Criteria andTableSchemBetween(String value1, String value2) {
            addCriterion("TABLE_SCHEM between", value1, value2, "tableSchem");
            return (Criteria) this;
        }

        public Criteria andTableSchemNotBetween(String value1, String value2) {
            addCriterion("TABLE_SCHEM not between", value1, value2, "tableSchem");
            return (Criteria) this;
        }

        public Criteria andTableNameIsNull() {
            addCriterion("TABLE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andTableNameIsNotNull() {
            addCriterion("TABLE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andTableNameEqualTo(String value) {
            addCriterion("TABLE_NAME =", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameNotEqualTo(String value) {
            addCriterion("TABLE_NAME <>", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameGreaterThan(String value) {
            addCriterion("TABLE_NAME >", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameGreaterThanOrEqualTo(String value) {
            addCriterion("TABLE_NAME >=", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameLessThan(String value) {
            addCriterion("TABLE_NAME <", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameLessThanOrEqualTo(String value) {
            addCriterion("TABLE_NAME <=", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameLike(String value) {
            addCriterion("TABLE_NAME like", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameNotLike(String value) {
            addCriterion("TABLE_NAME not like", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameIn(List<String> values) {
            addCriterion("TABLE_NAME in", values, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameNotIn(List<String> values) {
            addCriterion("TABLE_NAME not in", values, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameBetween(String value1, String value2) {
            addCriterion("TABLE_NAME between", value1, value2, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameNotBetween(String value1, String value2) {
            addCriterion("TABLE_NAME not between", value1, value2, "tableName");
            return (Criteria) this;
        }

        public Criteria andDataSourceDefintionIsNull() {
            addCriterion("DATA_SOURCE_DEFINTION is null");
            return (Criteria) this;
        }

        public Criteria andDataSourceDefintionIsNotNull() {
            addCriterion("DATA_SOURCE_DEFINTION is not null");
            return (Criteria) this;
        }

        public Criteria andDataSourceDefintionEqualTo(String value) {
            addCriterion("DATA_SOURCE_DEFINTION =", value, "dataSourceDefintion");
            return (Criteria) this;
        }

        public Criteria andDataSourceDefintionNotEqualTo(String value) {
            addCriterion("DATA_SOURCE_DEFINTION <>", value, "dataSourceDefintion");
            return (Criteria) this;
        }

        public Criteria andDataSourceDefintionGreaterThan(String value) {
            addCriterion("DATA_SOURCE_DEFINTION >", value, "dataSourceDefintion");
            return (Criteria) this;
        }

        public Criteria andDataSourceDefintionGreaterThanOrEqualTo(String value) {
            addCriterion("DATA_SOURCE_DEFINTION >=", value, "dataSourceDefintion");
            return (Criteria) this;
        }

        public Criteria andDataSourceDefintionLessThan(String value) {
            addCriterion("DATA_SOURCE_DEFINTION <", value, "dataSourceDefintion");
            return (Criteria) this;
        }

        public Criteria andDataSourceDefintionLessThanOrEqualTo(String value) {
            addCriterion("DATA_SOURCE_DEFINTION <=", value, "dataSourceDefintion");
            return (Criteria) this;
        }

        public Criteria andDataSourceDefintionLike(String value) {
            addCriterion("DATA_SOURCE_DEFINTION like", value, "dataSourceDefintion");
            return (Criteria) this;
        }

        public Criteria andDataSourceDefintionNotLike(String value) {
            addCriterion("DATA_SOURCE_DEFINTION not like", value, "dataSourceDefintion");
            return (Criteria) this;
        }

        public Criteria andDataSourceDefintionIn(List<String> values) {
            addCriterion("DATA_SOURCE_DEFINTION in", values, "dataSourceDefintion");
            return (Criteria) this;
        }

        public Criteria andDataSourceDefintionNotIn(List<String> values) {
            addCriterion("DATA_SOURCE_DEFINTION not in", values, "dataSourceDefintion");
            return (Criteria) this;
        }

        public Criteria andDataSourceDefintionBetween(String value1, String value2) {
            addCriterion("DATA_SOURCE_DEFINTION between", value1, value2, "dataSourceDefintion");
            return (Criteria) this;
        }

        public Criteria andDataSourceDefintionNotBetween(String value1, String value2) {
            addCriterion("DATA_SOURCE_DEFINTION not between", value1, value2, "dataSourceDefintion");
            return (Criteria) this;
        }

        public Criteria andFilePathIsNull() {
            addCriterion("FILE_PATH is null");
            return (Criteria) this;
        }

        public Criteria andFilePathIsNotNull() {
            addCriterion("FILE_PATH is not null");
            return (Criteria) this;
        }

        public Criteria andFilePathEqualTo(String value) {
            addCriterion("FILE_PATH =", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathNotEqualTo(String value) {
            addCriterion("FILE_PATH <>", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathGreaterThan(String value) {
            addCriterion("FILE_PATH >", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathGreaterThanOrEqualTo(String value) {
            addCriterion("FILE_PATH >=", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathLessThan(String value) {
            addCriterion("FILE_PATH <", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathLessThanOrEqualTo(String value) {
            addCriterion("FILE_PATH <=", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathLike(String value) {
            addCriterion("FILE_PATH like", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathNotLike(String value) {
            addCriterion("FILE_PATH not like", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathIn(List<String> values) {
            addCriterion("FILE_PATH in", values, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathNotIn(List<String> values) {
            addCriterion("FILE_PATH not in", values, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathBetween(String value1, String value2) {
            addCriterion("FILE_PATH between", value1, value2, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathNotBetween(String value1, String value2) {
            addCriterion("FILE_PATH not between", value1, value2, "filePath");
            return (Criteria) this;
        }

        public Criteria andFileEncodingIsNull() {
            addCriterion("FILE_ENCODING is null");
            return (Criteria) this;
        }

        public Criteria andFileEncodingIsNotNull() {
            addCriterion("FILE_ENCODING is not null");
            return (Criteria) this;
        }

        public Criteria andFileEncodingEqualTo(String value) {
            addCriterion("FILE_ENCODING =", value, "fileEncoding");
            return (Criteria) this;
        }

        public Criteria andFileEncodingNotEqualTo(String value) {
            addCriterion("FILE_ENCODING <>", value, "fileEncoding");
            return (Criteria) this;
        }

        public Criteria andFileEncodingGreaterThan(String value) {
            addCriterion("FILE_ENCODING >", value, "fileEncoding");
            return (Criteria) this;
        }

        public Criteria andFileEncodingGreaterThanOrEqualTo(String value) {
            addCriterion("FILE_ENCODING >=", value, "fileEncoding");
            return (Criteria) this;
        }

        public Criteria andFileEncodingLessThan(String value) {
            addCriterion("FILE_ENCODING <", value, "fileEncoding");
            return (Criteria) this;
        }

        public Criteria andFileEncodingLessThanOrEqualTo(String value) {
            addCriterion("FILE_ENCODING <=", value, "fileEncoding");
            return (Criteria) this;
        }

        public Criteria andFileEncodingLike(String value) {
            addCriterion("FILE_ENCODING like", value, "fileEncoding");
            return (Criteria) this;
        }

        public Criteria andFileEncodingNotLike(String value) {
            addCriterion("FILE_ENCODING not like", value, "fileEncoding");
            return (Criteria) this;
        }

        public Criteria andFileEncodingIn(List<String> values) {
            addCriterion("FILE_ENCODING in", values, "fileEncoding");
            return (Criteria) this;
        }

        public Criteria andFileEncodingNotIn(List<String> values) {
            addCriterion("FILE_ENCODING not in", values, "fileEncoding");
            return (Criteria) this;
        }

        public Criteria andFileEncodingBetween(String value1, String value2) {
            addCriterion("FILE_ENCODING between", value1, value2, "fileEncoding");
            return (Criteria) this;
        }

        public Criteria andFileEncodingNotBetween(String value1, String value2) {
            addCriterion("FILE_ENCODING not between", value1, value2, "fileEncoding");
            return (Criteria) this;
        }

        public Criteria andFieldSeparatorIsNull() {
            addCriterion("FIELD_SEPARATOR is null");
            return (Criteria) this;
        }

        public Criteria andFieldSeparatorIsNotNull() {
            addCriterion("FIELD_SEPARATOR is not null");
            return (Criteria) this;
        }

        public Criteria andFieldSeparatorEqualTo(String value) {
            addCriterion("FIELD_SEPARATOR =", value, "fieldSeparator");
            return (Criteria) this;
        }

        public Criteria andFieldSeparatorNotEqualTo(String value) {
            addCriterion("FIELD_SEPARATOR <>", value, "fieldSeparator");
            return (Criteria) this;
        }

        public Criteria andFieldSeparatorGreaterThan(String value) {
            addCriterion("FIELD_SEPARATOR >", value, "fieldSeparator");
            return (Criteria) this;
        }

        public Criteria andFieldSeparatorGreaterThanOrEqualTo(String value) {
            addCriterion("FIELD_SEPARATOR >=", value, "fieldSeparator");
            return (Criteria) this;
        }

        public Criteria andFieldSeparatorLessThan(String value) {
            addCriterion("FIELD_SEPARATOR <", value, "fieldSeparator");
            return (Criteria) this;
        }

        public Criteria andFieldSeparatorLessThanOrEqualTo(String value) {
            addCriterion("FIELD_SEPARATOR <=", value, "fieldSeparator");
            return (Criteria) this;
        }

        public Criteria andFieldSeparatorLike(String value) {
            addCriterion("FIELD_SEPARATOR like", value, "fieldSeparator");
            return (Criteria) this;
        }

        public Criteria andFieldSeparatorNotLike(String value) {
            addCriterion("FIELD_SEPARATOR not like", value, "fieldSeparator");
            return (Criteria) this;
        }

        public Criteria andFieldSeparatorIn(List<String> values) {
            addCriterion("FIELD_SEPARATOR in", values, "fieldSeparator");
            return (Criteria) this;
        }

        public Criteria andFieldSeparatorNotIn(List<String> values) {
            addCriterion("FIELD_SEPARATOR not in", values, "fieldSeparator");
            return (Criteria) this;
        }

        public Criteria andFieldSeparatorBetween(String value1, String value2) {
            addCriterion("FIELD_SEPARATOR between", value1, value2, "fieldSeparator");
            return (Criteria) this;
        }

        public Criteria andFieldSeparatorNotBetween(String value1, String value2) {
            addCriterion("FIELD_SEPARATOR not between", value1, value2, "fieldSeparator");
            return (Criteria) this;
        }

        public Criteria andVarcharSeparatorIsNull() {
            addCriterion("VARCHAR_SEPARATOR is null");
            return (Criteria) this;
        }

        public Criteria andVarcharSeparatorIsNotNull() {
            addCriterion("VARCHAR_SEPARATOR is not null");
            return (Criteria) this;
        }

        public Criteria andVarcharSeparatorEqualTo(String value) {
            addCriterion("VARCHAR_SEPARATOR =", value, "varcharSeparator");
            return (Criteria) this;
        }

        public Criteria andVarcharSeparatorNotEqualTo(String value) {
            addCriterion("VARCHAR_SEPARATOR <>", value, "varcharSeparator");
            return (Criteria) this;
        }

        public Criteria andVarcharSeparatorGreaterThan(String value) {
            addCriterion("VARCHAR_SEPARATOR >", value, "varcharSeparator");
            return (Criteria) this;
        }

        public Criteria andVarcharSeparatorGreaterThanOrEqualTo(String value) {
            addCriterion("VARCHAR_SEPARATOR >=", value, "varcharSeparator");
            return (Criteria) this;
        }

        public Criteria andVarcharSeparatorLessThan(String value) {
            addCriterion("VARCHAR_SEPARATOR <", value, "varcharSeparator");
            return (Criteria) this;
        }

        public Criteria andVarcharSeparatorLessThanOrEqualTo(String value) {
            addCriterion("VARCHAR_SEPARATOR <=", value, "varcharSeparator");
            return (Criteria) this;
        }

        public Criteria andVarcharSeparatorLike(String value) {
            addCriterion("VARCHAR_SEPARATOR like", value, "varcharSeparator");
            return (Criteria) this;
        }

        public Criteria andVarcharSeparatorNotLike(String value) {
            addCriterion("VARCHAR_SEPARATOR not like", value, "varcharSeparator");
            return (Criteria) this;
        }

        public Criteria andVarcharSeparatorIn(List<String> values) {
            addCriterion("VARCHAR_SEPARATOR in", values, "varcharSeparator");
            return (Criteria) this;
        }

        public Criteria andVarcharSeparatorNotIn(List<String> values) {
            addCriterion("VARCHAR_SEPARATOR not in", values, "varcharSeparator");
            return (Criteria) this;
        }

        public Criteria andVarcharSeparatorBetween(String value1, String value2) {
            addCriterion("VARCHAR_SEPARATOR between", value1, value2, "varcharSeparator");
            return (Criteria) this;
        }

        public Criteria andVarcharSeparatorNotBetween(String value1, String value2) {
            addCriterion("VARCHAR_SEPARATOR not between", value1, value2, "varcharSeparator");
            return (Criteria) this;
        }

        public Criteria andLongvarcharSeparatorIsNull() {
            addCriterion("LONGVARCHAR_SEPARATOR is null");
            return (Criteria) this;
        }

        public Criteria andLongvarcharSeparatorIsNotNull() {
            addCriterion("LONGVARCHAR_SEPARATOR is not null");
            return (Criteria) this;
        }

        public Criteria andLongvarcharSeparatorEqualTo(String value) {
            addCriterion("LONGVARCHAR_SEPARATOR =", value, "longvarcharSeparator");
            return (Criteria) this;
        }

        public Criteria andLongvarcharSeparatorNotEqualTo(String value) {
            addCriterion("LONGVARCHAR_SEPARATOR <>", value, "longvarcharSeparator");
            return (Criteria) this;
        }

        public Criteria andLongvarcharSeparatorGreaterThan(String value) {
            addCriterion("LONGVARCHAR_SEPARATOR >", value, "longvarcharSeparator");
            return (Criteria) this;
        }

        public Criteria andLongvarcharSeparatorGreaterThanOrEqualTo(String value) {
            addCriterion("LONGVARCHAR_SEPARATOR >=", value, "longvarcharSeparator");
            return (Criteria) this;
        }

        public Criteria andLongvarcharSeparatorLessThan(String value) {
            addCriterion("LONGVARCHAR_SEPARATOR <", value, "longvarcharSeparator");
            return (Criteria) this;
        }

        public Criteria andLongvarcharSeparatorLessThanOrEqualTo(String value) {
            addCriterion("LONGVARCHAR_SEPARATOR <=", value, "longvarcharSeparator");
            return (Criteria) this;
        }

        public Criteria andLongvarcharSeparatorLike(String value) {
            addCriterion("LONGVARCHAR_SEPARATOR like", value, "longvarcharSeparator");
            return (Criteria) this;
        }

        public Criteria andLongvarcharSeparatorNotLike(String value) {
            addCriterion("LONGVARCHAR_SEPARATOR not like", value, "longvarcharSeparator");
            return (Criteria) this;
        }

        public Criteria andLongvarcharSeparatorIn(List<String> values) {
            addCriterion("LONGVARCHAR_SEPARATOR in", values, "longvarcharSeparator");
            return (Criteria) this;
        }

        public Criteria andLongvarcharSeparatorNotIn(List<String> values) {
            addCriterion("LONGVARCHAR_SEPARATOR not in", values, "longvarcharSeparator");
            return (Criteria) this;
        }

        public Criteria andLongvarcharSeparatorBetween(String value1, String value2) {
            addCriterion("LONGVARCHAR_SEPARATOR between", value1, value2, "longvarcharSeparator");
            return (Criteria) this;
        }

        public Criteria andLongvarcharSeparatorNotBetween(String value1, String value2) {
            addCriterion("LONGVARCHAR_SEPARATOR not between", value1, value2, "longvarcharSeparator");
            return (Criteria) this;
        }

        public Criteria andIsIgnoreFirstIsNull() {
            addCriterion("IS_IGNORE_FIRST is null");
            return (Criteria) this;
        }

        public Criteria andIsIgnoreFirstIsNotNull() {
            addCriterion("IS_IGNORE_FIRST is not null");
            return (Criteria) this;
        }

        public Criteria andIsIgnoreFirstEqualTo(Boolean value) {
            addCriterion("IS_IGNORE_FIRST =", value, "isIgnoreFirst");
            return (Criteria) this;
        }

        public Criteria andIsIgnoreFirstNotEqualTo(Boolean value) {
            addCriterion("IS_IGNORE_FIRST <>", value, "isIgnoreFirst");
            return (Criteria) this;
        }

        public Criteria andIsIgnoreFirstGreaterThan(Boolean value) {
            addCriterion("IS_IGNORE_FIRST >", value, "isIgnoreFirst");
            return (Criteria) this;
        }

        public Criteria andIsIgnoreFirstGreaterThanOrEqualTo(Boolean value) {
            addCriterion("IS_IGNORE_FIRST >=", value, "isIgnoreFirst");
            return (Criteria) this;
        }

        public Criteria andIsIgnoreFirstLessThan(Boolean value) {
            addCriterion("IS_IGNORE_FIRST <", value, "isIgnoreFirst");
            return (Criteria) this;
        }

        public Criteria andIsIgnoreFirstLessThanOrEqualTo(Boolean value) {
            addCriterion("IS_IGNORE_FIRST <=", value, "isIgnoreFirst");
            return (Criteria) this;
        }

        public Criteria andIsIgnoreFirstIn(List<Boolean> values) {
            addCriterion("IS_IGNORE_FIRST in", values, "isIgnoreFirst");
            return (Criteria) this;
        }

        public Criteria andIsIgnoreFirstNotIn(List<Boolean> values) {
            addCriterion("IS_IGNORE_FIRST not in", values, "isIgnoreFirst");
            return (Criteria) this;
        }

        public Criteria andIsIgnoreFirstBetween(Boolean value1, Boolean value2) {
            addCriterion("IS_IGNORE_FIRST between", value1, value2, "isIgnoreFirst");
            return (Criteria) this;
        }

        public Criteria andIsIgnoreFirstNotBetween(Boolean value1, Boolean value2) {
            addCriterion("IS_IGNORE_FIRST not between", value1, value2, "isIgnoreFirst");
            return (Criteria) this;
        }

        public Criteria andIsAllQuotedIsNull() {
            addCriterion("IS_ALL_QUOTED is null");
            return (Criteria) this;
        }

        public Criteria andIsAllQuotedIsNotNull() {
            addCriterion("IS_ALL_QUOTED is not null");
            return (Criteria) this;
        }

        public Criteria andIsAllQuotedEqualTo(Boolean value) {
            addCriterion("IS_ALL_QUOTED =", value, "isAllQuoted");
            return (Criteria) this;
        }

        public Criteria andIsAllQuotedNotEqualTo(Boolean value) {
            addCriterion("IS_ALL_QUOTED <>", value, "isAllQuoted");
            return (Criteria) this;
        }

        public Criteria andIsAllQuotedGreaterThan(Boolean value) {
            addCriterion("IS_ALL_QUOTED >", value, "isAllQuoted");
            return (Criteria) this;
        }

        public Criteria andIsAllQuotedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("IS_ALL_QUOTED >=", value, "isAllQuoted");
            return (Criteria) this;
        }

        public Criteria andIsAllQuotedLessThan(Boolean value) {
            addCriterion("IS_ALL_QUOTED <", value, "isAllQuoted");
            return (Criteria) this;
        }

        public Criteria andIsAllQuotedLessThanOrEqualTo(Boolean value) {
            addCriterion("IS_ALL_QUOTED <=", value, "isAllQuoted");
            return (Criteria) this;
        }

        public Criteria andIsAllQuotedIn(List<Boolean> values) {
            addCriterion("IS_ALL_QUOTED in", values, "isAllQuoted");
            return (Criteria) this;
        }

        public Criteria andIsAllQuotedNotIn(List<Boolean> values) {
            addCriterion("IS_ALL_QUOTED not in", values, "isAllQuoted");
            return (Criteria) this;
        }

        public Criteria andIsAllQuotedBetween(Boolean value1, Boolean value2) {
            addCriterion("IS_ALL_QUOTED between", value1, value2, "isAllQuoted");
            return (Criteria) this;
        }

        public Criteria andIsAllQuotedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("IS_ALL_QUOTED not between", value1, value2, "isAllQuoted");
            return (Criteria) this;
        }

        public Criteria andIsQuotedIsNull() {
            addCriterion("IS_QUOTED is null");
            return (Criteria) this;
        }

        public Criteria andIsQuotedIsNotNull() {
            addCriterion("IS_QUOTED is not null");
            return (Criteria) this;
        }

        public Criteria andIsQuotedEqualTo(Boolean value) {
            addCriterion("IS_QUOTED =", value, "isQuoted");
            return (Criteria) this;
        }

        public Criteria andIsQuotedNotEqualTo(Boolean value) {
            addCriterion("IS_QUOTED <>", value, "isQuoted");
            return (Criteria) this;
        }

        public Criteria andIsQuotedGreaterThan(Boolean value) {
            addCriterion("IS_QUOTED >", value, "isQuoted");
            return (Criteria) this;
        }

        public Criteria andIsQuotedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("IS_QUOTED >=", value, "isQuoted");
            return (Criteria) this;
        }

        public Criteria andIsQuotedLessThan(Boolean value) {
            addCriterion("IS_QUOTED <", value, "isQuoted");
            return (Criteria) this;
        }

        public Criteria andIsQuotedLessThanOrEqualTo(Boolean value) {
            addCriterion("IS_QUOTED <=", value, "isQuoted");
            return (Criteria) this;
        }

        public Criteria andIsQuotedIn(List<Boolean> values) {
            addCriterion("IS_QUOTED in", values, "isQuoted");
            return (Criteria) this;
        }

        public Criteria andIsQuotedNotIn(List<Boolean> values) {
            addCriterion("IS_QUOTED not in", values, "isQuoted");
            return (Criteria) this;
        }

        public Criteria andIsQuotedBetween(Boolean value1, Boolean value2) {
            addCriterion("IS_QUOTED between", value1, value2, "isQuoted");
            return (Criteria) this;
        }

        public Criteria andIsQuotedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("IS_QUOTED not between", value1, value2, "isQuoted");
            return (Criteria) this;
        }

        public Criteria andIsDescIsNull() {
            addCriterion("IS_DESC is null");
            return (Criteria) this;
        }

        public Criteria andIsDescIsNotNull() {
            addCriterion("IS_DESC is not null");
            return (Criteria) this;
        }

        public Criteria andIsDescEqualTo(Boolean value) {
            addCriterion("IS_DESC =", value, "isDesc");
            return (Criteria) this;
        }

        public Criteria andIsDescNotEqualTo(Boolean value) {
            addCriterion("IS_DESC <>", value, "isDesc");
            return (Criteria) this;
        }

        public Criteria andIsDescGreaterThan(Boolean value) {
            addCriterion("IS_DESC >", value, "isDesc");
            return (Criteria) this;
        }

        public Criteria andIsDescGreaterThanOrEqualTo(Boolean value) {
            addCriterion("IS_DESC >=", value, "isDesc");
            return (Criteria) this;
        }

        public Criteria andIsDescLessThan(Boolean value) {
            addCriterion("IS_DESC <", value, "isDesc");
            return (Criteria) this;
        }

        public Criteria andIsDescLessThanOrEqualTo(Boolean value) {
            addCriterion("IS_DESC <=", value, "isDesc");
            return (Criteria) this;
        }

        public Criteria andIsDescIn(List<Boolean> values) {
            addCriterion("IS_DESC in", values, "isDesc");
            return (Criteria) this;
        }

        public Criteria andIsDescNotIn(List<Boolean> values) {
            addCriterion("IS_DESC not in", values, "isDesc");
            return (Criteria) this;
        }

        public Criteria andIsDescBetween(Boolean value1, Boolean value2) {
            addCriterion("IS_DESC between", value1, value2, "isDesc");
            return (Criteria) this;
        }

        public Criteria andIsDescNotBetween(Boolean value1, Boolean value2) {
            addCriterion("IS_DESC not between", value1, value2, "isDesc");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table INFORMATION_SCHEMA.SYSTEM_TEXTTABLES
     *
     * @mbggenerated do_not_delete_during_merge Sat Mar 21 14:24:50 ICT 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table INFORMATION_SCHEMA.SYSTEM_TEXTTABLES
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}