package com.pratz.dao.table.model;

public class SystemTypeinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.TYPE_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.DATA_TYPE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private Short dataType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.PRECISION
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private Integer precision;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.LITERAL_PREFIX
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String literalPrefix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.LITERAL_SUFFIX
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String literalSuffix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.CREATE_PARAMS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String createParams;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.NULLABLE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private Short nullable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.CASE_SENSITIVE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private Boolean caseSensitive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.SEARCHABLE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private Integer searchable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.UNSIGNED_ATTRIBUTE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private Boolean unsignedAttribute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.FIXED_PREC_SCALE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private Boolean fixedPrecScale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.AUTO_INCREMENT
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private Boolean autoIncrement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.LOCAL_TYPE_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String localTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.MINIMUM_SCALE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private Short minimumScale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.MAXIMUM_SCALE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private Short maximumScale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.SQL_DATA_TYPE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private Integer sqlDataType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.SQL_DATETIME_SUB
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private Integer sqlDatetimeSub;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.NUM_PREC_RADIX
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private Integer numPrecRadix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.INTERVAL_PRECISION
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private Integer intervalPrecision;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.TYPE_NAME
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_TYPEINFO.TYPE_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.TYPE_NAME
     *
     * @param typeName the value for INFORMATION_SCHEMA.SYSTEM_TYPEINFO.TYPE_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.DATA_TYPE
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_TYPEINFO.DATA_TYPE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public Short getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.DATA_TYPE
     *
     * @param dataType the value for INFORMATION_SCHEMA.SYSTEM_TYPEINFO.DATA_TYPE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setDataType(Short dataType) {
        this.dataType = dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.PRECISION
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_TYPEINFO.PRECISION
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public Integer getPrecision() {
        return precision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.PRECISION
     *
     * @param precision the value for INFORMATION_SCHEMA.SYSTEM_TYPEINFO.PRECISION
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setPrecision(Integer precision) {
        this.precision = precision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.LITERAL_PREFIX
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_TYPEINFO.LITERAL_PREFIX
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getLiteralPrefix() {
        return literalPrefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.LITERAL_PREFIX
     *
     * @param literalPrefix the value for INFORMATION_SCHEMA.SYSTEM_TYPEINFO.LITERAL_PREFIX
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setLiteralPrefix(String literalPrefix) {
        this.literalPrefix = literalPrefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.LITERAL_SUFFIX
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_TYPEINFO.LITERAL_SUFFIX
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getLiteralSuffix() {
        return literalSuffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.LITERAL_SUFFIX
     *
     * @param literalSuffix the value for INFORMATION_SCHEMA.SYSTEM_TYPEINFO.LITERAL_SUFFIX
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setLiteralSuffix(String literalSuffix) {
        this.literalSuffix = literalSuffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.CREATE_PARAMS
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_TYPEINFO.CREATE_PARAMS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getCreateParams() {
        return createParams;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.CREATE_PARAMS
     *
     * @param createParams the value for INFORMATION_SCHEMA.SYSTEM_TYPEINFO.CREATE_PARAMS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setCreateParams(String createParams) {
        this.createParams = createParams;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.NULLABLE
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_TYPEINFO.NULLABLE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public Short getNullable() {
        return nullable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.NULLABLE
     *
     * @param nullable the value for INFORMATION_SCHEMA.SYSTEM_TYPEINFO.NULLABLE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setNullable(Short nullable) {
        this.nullable = nullable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.CASE_SENSITIVE
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_TYPEINFO.CASE_SENSITIVE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public Boolean getCaseSensitive() {
        return caseSensitive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.CASE_SENSITIVE
     *
     * @param caseSensitive the value for INFORMATION_SCHEMA.SYSTEM_TYPEINFO.CASE_SENSITIVE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setCaseSensitive(Boolean caseSensitive) {
        this.caseSensitive = caseSensitive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.SEARCHABLE
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_TYPEINFO.SEARCHABLE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public Integer getSearchable() {
        return searchable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.SEARCHABLE
     *
     * @param searchable the value for INFORMATION_SCHEMA.SYSTEM_TYPEINFO.SEARCHABLE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setSearchable(Integer searchable) {
        this.searchable = searchable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.UNSIGNED_ATTRIBUTE
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_TYPEINFO.UNSIGNED_ATTRIBUTE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public Boolean getUnsignedAttribute() {
        return unsignedAttribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.UNSIGNED_ATTRIBUTE
     *
     * @param unsignedAttribute the value for INFORMATION_SCHEMA.SYSTEM_TYPEINFO.UNSIGNED_ATTRIBUTE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setUnsignedAttribute(Boolean unsignedAttribute) {
        this.unsignedAttribute = unsignedAttribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.FIXED_PREC_SCALE
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_TYPEINFO.FIXED_PREC_SCALE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public Boolean getFixedPrecScale() {
        return fixedPrecScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.FIXED_PREC_SCALE
     *
     * @param fixedPrecScale the value for INFORMATION_SCHEMA.SYSTEM_TYPEINFO.FIXED_PREC_SCALE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setFixedPrecScale(Boolean fixedPrecScale) {
        this.fixedPrecScale = fixedPrecScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.AUTO_INCREMENT
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_TYPEINFO.AUTO_INCREMENT
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public Boolean getAutoIncrement() {
        return autoIncrement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.AUTO_INCREMENT
     *
     * @param autoIncrement the value for INFORMATION_SCHEMA.SYSTEM_TYPEINFO.AUTO_INCREMENT
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setAutoIncrement(Boolean autoIncrement) {
        this.autoIncrement = autoIncrement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.LOCAL_TYPE_NAME
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_TYPEINFO.LOCAL_TYPE_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getLocalTypeName() {
        return localTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.LOCAL_TYPE_NAME
     *
     * @param localTypeName the value for INFORMATION_SCHEMA.SYSTEM_TYPEINFO.LOCAL_TYPE_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setLocalTypeName(String localTypeName) {
        this.localTypeName = localTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.MINIMUM_SCALE
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_TYPEINFO.MINIMUM_SCALE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public Short getMinimumScale() {
        return minimumScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.MINIMUM_SCALE
     *
     * @param minimumScale the value for INFORMATION_SCHEMA.SYSTEM_TYPEINFO.MINIMUM_SCALE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setMinimumScale(Short minimumScale) {
        this.minimumScale = minimumScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.MAXIMUM_SCALE
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_TYPEINFO.MAXIMUM_SCALE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public Short getMaximumScale() {
        return maximumScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.MAXIMUM_SCALE
     *
     * @param maximumScale the value for INFORMATION_SCHEMA.SYSTEM_TYPEINFO.MAXIMUM_SCALE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setMaximumScale(Short maximumScale) {
        this.maximumScale = maximumScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.SQL_DATA_TYPE
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_TYPEINFO.SQL_DATA_TYPE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public Integer getSqlDataType() {
        return sqlDataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.SQL_DATA_TYPE
     *
     * @param sqlDataType the value for INFORMATION_SCHEMA.SYSTEM_TYPEINFO.SQL_DATA_TYPE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setSqlDataType(Integer sqlDataType) {
        this.sqlDataType = sqlDataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.SQL_DATETIME_SUB
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_TYPEINFO.SQL_DATETIME_SUB
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public Integer getSqlDatetimeSub() {
        return sqlDatetimeSub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.SQL_DATETIME_SUB
     *
     * @param sqlDatetimeSub the value for INFORMATION_SCHEMA.SYSTEM_TYPEINFO.SQL_DATETIME_SUB
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setSqlDatetimeSub(Integer sqlDatetimeSub) {
        this.sqlDatetimeSub = sqlDatetimeSub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.NUM_PREC_RADIX
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_TYPEINFO.NUM_PREC_RADIX
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public Integer getNumPrecRadix() {
        return numPrecRadix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.NUM_PREC_RADIX
     *
     * @param numPrecRadix the value for INFORMATION_SCHEMA.SYSTEM_TYPEINFO.NUM_PREC_RADIX
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setNumPrecRadix(Integer numPrecRadix) {
        this.numPrecRadix = numPrecRadix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.INTERVAL_PRECISION
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_TYPEINFO.INTERVAL_PRECISION
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public Integer getIntervalPrecision() {
        return intervalPrecision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_TYPEINFO.INTERVAL_PRECISION
     *
     * @param intervalPrecision the value for INFORMATION_SCHEMA.SYSTEM_TYPEINFO.INTERVAL_PRECISION
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setIntervalPrecision(Integer intervalPrecision) {
        this.intervalPrecision = intervalPrecision;
    }
}