package com.pratz.dao.table.model;

public class SystemCacheinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_CACHEINFO.CACHE_FILE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String cacheFile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_CACHEINFO.MAX_CACHE_COUNT
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private Long maxCacheCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_CACHEINFO.MAX_CACHE_BYTES
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private Long maxCacheBytes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_CACHEINFO.CACHE_SIZE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private Long cacheSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_CACHEINFO.CACHE_BYTES
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private Long cacheBytes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_CACHEINFO.FILE_LOST_BYTES
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private Long fileLostBytes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_CACHEINFO.FILE_FREE_POS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private Long fileFreePos;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_CACHEINFO.CACHE_FILE
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_CACHEINFO.CACHE_FILE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getCacheFile() {
        return cacheFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_CACHEINFO.CACHE_FILE
     *
     * @param cacheFile the value for INFORMATION_SCHEMA.SYSTEM_CACHEINFO.CACHE_FILE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setCacheFile(String cacheFile) {
        this.cacheFile = cacheFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_CACHEINFO.MAX_CACHE_COUNT
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_CACHEINFO.MAX_CACHE_COUNT
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public Long getMaxCacheCount() {
        return maxCacheCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_CACHEINFO.MAX_CACHE_COUNT
     *
     * @param maxCacheCount the value for INFORMATION_SCHEMA.SYSTEM_CACHEINFO.MAX_CACHE_COUNT
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setMaxCacheCount(Long maxCacheCount) {
        this.maxCacheCount = maxCacheCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_CACHEINFO.MAX_CACHE_BYTES
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_CACHEINFO.MAX_CACHE_BYTES
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public Long getMaxCacheBytes() {
        return maxCacheBytes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_CACHEINFO.MAX_CACHE_BYTES
     *
     * @param maxCacheBytes the value for INFORMATION_SCHEMA.SYSTEM_CACHEINFO.MAX_CACHE_BYTES
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setMaxCacheBytes(Long maxCacheBytes) {
        this.maxCacheBytes = maxCacheBytes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_CACHEINFO.CACHE_SIZE
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_CACHEINFO.CACHE_SIZE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public Long getCacheSize() {
        return cacheSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_CACHEINFO.CACHE_SIZE
     *
     * @param cacheSize the value for INFORMATION_SCHEMA.SYSTEM_CACHEINFO.CACHE_SIZE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setCacheSize(Long cacheSize) {
        this.cacheSize = cacheSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_CACHEINFO.CACHE_BYTES
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_CACHEINFO.CACHE_BYTES
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public Long getCacheBytes() {
        return cacheBytes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_CACHEINFO.CACHE_BYTES
     *
     * @param cacheBytes the value for INFORMATION_SCHEMA.SYSTEM_CACHEINFO.CACHE_BYTES
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setCacheBytes(Long cacheBytes) {
        this.cacheBytes = cacheBytes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_CACHEINFO.FILE_LOST_BYTES
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_CACHEINFO.FILE_LOST_BYTES
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public Long getFileLostBytes() {
        return fileLostBytes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_CACHEINFO.FILE_LOST_BYTES
     *
     * @param fileLostBytes the value for INFORMATION_SCHEMA.SYSTEM_CACHEINFO.FILE_LOST_BYTES
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setFileLostBytes(Long fileLostBytes) {
        this.fileLostBytes = fileLostBytes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_CACHEINFO.FILE_FREE_POS
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_CACHEINFO.FILE_FREE_POS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public Long getFileFreePos() {
        return fileFreePos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_CACHEINFO.FILE_FREE_POS
     *
     * @param fileFreePos the value for INFORMATION_SCHEMA.SYSTEM_CACHEINFO.FILE_FREE_POS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setFileFreePos(Long fileFreePos) {
        this.fileFreePos = fileFreePos;
    }
}