package com.pratz.dao.table.model;

public class SystemIndexinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_INDEXINFO.TABLE_CAT
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    private String tableCat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_INDEXINFO.TABLE_SCHEM
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    private String tableSchem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_INDEXINFO.TABLE_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    private String tableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_INDEXINFO.NON_UNIQUE
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    private Boolean nonUnique;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_INDEXINFO.INDEX_QUALIFIER
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    private String indexQualifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_INDEXINFO.INDEX_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    private String indexName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_INDEXINFO.TYPE
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    private Short type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_INDEXINFO.ORDINAL_POSITION
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    private Short ordinalPosition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_INDEXINFO.COLUMN_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    private String columnName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_INDEXINFO.ASC_OR_DESC
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    private String ascOrDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_INDEXINFO.CARDINALITY
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    private Integer cardinality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_INDEXINFO.PAGES
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    private Integer pages;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_INDEXINFO.FILTER_CONDITION
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    private String filterCondition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_INDEXINFO.ROW_CARDINALITY
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    private Integer rowCardinality;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_INDEXINFO.TABLE_CAT
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_INDEXINFO.TABLE_CAT
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    public String getTableCat() {
        return tableCat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_INDEXINFO.TABLE_CAT
     *
     * @param tableCat the value for INFORMATION_SCHEMA.SYSTEM_INDEXINFO.TABLE_CAT
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    public void setTableCat(String tableCat) {
        this.tableCat = tableCat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_INDEXINFO.TABLE_SCHEM
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_INDEXINFO.TABLE_SCHEM
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    public String getTableSchem() {
        return tableSchem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_INDEXINFO.TABLE_SCHEM
     *
     * @param tableSchem the value for INFORMATION_SCHEMA.SYSTEM_INDEXINFO.TABLE_SCHEM
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    public void setTableSchem(String tableSchem) {
        this.tableSchem = tableSchem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_INDEXINFO.TABLE_NAME
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_INDEXINFO.TABLE_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_INDEXINFO.TABLE_NAME
     *
     * @param tableName the value for INFORMATION_SCHEMA.SYSTEM_INDEXINFO.TABLE_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_INDEXINFO.NON_UNIQUE
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_INDEXINFO.NON_UNIQUE
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    public Boolean getNonUnique() {
        return nonUnique;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_INDEXINFO.NON_UNIQUE
     *
     * @param nonUnique the value for INFORMATION_SCHEMA.SYSTEM_INDEXINFO.NON_UNIQUE
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    public void setNonUnique(Boolean nonUnique) {
        this.nonUnique = nonUnique;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_INDEXINFO.INDEX_QUALIFIER
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_INDEXINFO.INDEX_QUALIFIER
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    public String getIndexQualifier() {
        return indexQualifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_INDEXINFO.INDEX_QUALIFIER
     *
     * @param indexQualifier the value for INFORMATION_SCHEMA.SYSTEM_INDEXINFO.INDEX_QUALIFIER
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    public void setIndexQualifier(String indexQualifier) {
        this.indexQualifier = indexQualifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_INDEXINFO.INDEX_NAME
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_INDEXINFO.INDEX_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    public String getIndexName() {
        return indexName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_INDEXINFO.INDEX_NAME
     *
     * @param indexName the value for INFORMATION_SCHEMA.SYSTEM_INDEXINFO.INDEX_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    public void setIndexName(String indexName) {
        this.indexName = indexName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_INDEXINFO.TYPE
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_INDEXINFO.TYPE
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_INDEXINFO.TYPE
     *
     * @param type the value for INFORMATION_SCHEMA.SYSTEM_INDEXINFO.TYPE
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    public void setType(Short type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_INDEXINFO.ORDINAL_POSITION
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_INDEXINFO.ORDINAL_POSITION
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    public Short getOrdinalPosition() {
        return ordinalPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_INDEXINFO.ORDINAL_POSITION
     *
     * @param ordinalPosition the value for INFORMATION_SCHEMA.SYSTEM_INDEXINFO.ORDINAL_POSITION
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    public void setOrdinalPosition(Short ordinalPosition) {
        this.ordinalPosition = ordinalPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_INDEXINFO.COLUMN_NAME
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_INDEXINFO.COLUMN_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    public String getColumnName() {
        return columnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_INDEXINFO.COLUMN_NAME
     *
     * @param columnName the value for INFORMATION_SCHEMA.SYSTEM_INDEXINFO.COLUMN_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    public void setColumnName(String columnName) {
        this.columnName = columnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_INDEXINFO.ASC_OR_DESC
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_INDEXINFO.ASC_OR_DESC
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    public String getAscOrDesc() {
        return ascOrDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_INDEXINFO.ASC_OR_DESC
     *
     * @param ascOrDesc the value for INFORMATION_SCHEMA.SYSTEM_INDEXINFO.ASC_OR_DESC
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    public void setAscOrDesc(String ascOrDesc) {
        this.ascOrDesc = ascOrDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_INDEXINFO.CARDINALITY
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_INDEXINFO.CARDINALITY
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    public Integer getCardinality() {
        return cardinality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_INDEXINFO.CARDINALITY
     *
     * @param cardinality the value for INFORMATION_SCHEMA.SYSTEM_INDEXINFO.CARDINALITY
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    public void setCardinality(Integer cardinality) {
        this.cardinality = cardinality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_INDEXINFO.PAGES
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_INDEXINFO.PAGES
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    public Integer getPages() {
        return pages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_INDEXINFO.PAGES
     *
     * @param pages the value for INFORMATION_SCHEMA.SYSTEM_INDEXINFO.PAGES
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    public void setPages(Integer pages) {
        this.pages = pages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_INDEXINFO.FILTER_CONDITION
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_INDEXINFO.FILTER_CONDITION
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    public String getFilterCondition() {
        return filterCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_INDEXINFO.FILTER_CONDITION
     *
     * @param filterCondition the value for INFORMATION_SCHEMA.SYSTEM_INDEXINFO.FILTER_CONDITION
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    public void setFilterCondition(String filterCondition) {
        this.filterCondition = filterCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_INDEXINFO.ROW_CARDINALITY
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_INDEXINFO.ROW_CARDINALITY
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    public Integer getRowCardinality() {
        return rowCardinality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_INDEXINFO.ROW_CARDINALITY
     *
     * @param rowCardinality the value for INFORMATION_SCHEMA.SYSTEM_INDEXINFO.ROW_CARDINALITY
     *
     * @mbggenerated Sat Mar 21 14:24:49 ICT 2015
     */
    public void setRowCardinality(Integer rowCardinality) {
        this.rowCardinality = rowCardinality;
    }
}