package com.pratz.dao.table.model;

public class SystemTables {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_TABLES.TABLE_CAT
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String tableCat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_TABLES.TABLE_SCHEM
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String tableSchem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_TABLES.TABLE_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String tableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_TABLES.TABLE_TYPE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String tableType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_TABLES.REMARKS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_TABLES.TYPE_CAT
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String typeCat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_TABLES.TYPE_SCHEM
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String typeSchem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_TABLES.TYPE_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_TABLES.SELF_REFERENCING_COL_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String selfReferencingColName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_TABLES.REF_GENERATION
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String refGeneration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_TABLES.HSQLDB_TYPE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String hsqldbType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_TABLES.READ_ONLY
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private Boolean readOnly;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.SYSTEM_TABLES.COMMIT_ACTION
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String commitAction;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_TABLES.TABLE_CAT
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_TABLES.TABLE_CAT
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getTableCat() {
        return tableCat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_TABLES.TABLE_CAT
     *
     * @param tableCat the value for INFORMATION_SCHEMA.SYSTEM_TABLES.TABLE_CAT
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setTableCat(String tableCat) {
        this.tableCat = tableCat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_TABLES.TABLE_SCHEM
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_TABLES.TABLE_SCHEM
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getTableSchem() {
        return tableSchem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_TABLES.TABLE_SCHEM
     *
     * @param tableSchem the value for INFORMATION_SCHEMA.SYSTEM_TABLES.TABLE_SCHEM
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setTableSchem(String tableSchem) {
        this.tableSchem = tableSchem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_TABLES.TABLE_NAME
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_TABLES.TABLE_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_TABLES.TABLE_NAME
     *
     * @param tableName the value for INFORMATION_SCHEMA.SYSTEM_TABLES.TABLE_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_TABLES.TABLE_TYPE
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_TABLES.TABLE_TYPE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getTableType() {
        return tableType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_TABLES.TABLE_TYPE
     *
     * @param tableType the value for INFORMATION_SCHEMA.SYSTEM_TABLES.TABLE_TYPE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setTableType(String tableType) {
        this.tableType = tableType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_TABLES.REMARKS
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_TABLES.REMARKS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_TABLES.REMARKS
     *
     * @param remarks the value for INFORMATION_SCHEMA.SYSTEM_TABLES.REMARKS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_TABLES.TYPE_CAT
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_TABLES.TYPE_CAT
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getTypeCat() {
        return typeCat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_TABLES.TYPE_CAT
     *
     * @param typeCat the value for INFORMATION_SCHEMA.SYSTEM_TABLES.TYPE_CAT
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setTypeCat(String typeCat) {
        this.typeCat = typeCat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_TABLES.TYPE_SCHEM
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_TABLES.TYPE_SCHEM
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getTypeSchem() {
        return typeSchem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_TABLES.TYPE_SCHEM
     *
     * @param typeSchem the value for INFORMATION_SCHEMA.SYSTEM_TABLES.TYPE_SCHEM
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setTypeSchem(String typeSchem) {
        this.typeSchem = typeSchem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_TABLES.TYPE_NAME
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_TABLES.TYPE_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_TABLES.TYPE_NAME
     *
     * @param typeName the value for INFORMATION_SCHEMA.SYSTEM_TABLES.TYPE_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_TABLES.SELF_REFERENCING_COL_NAME
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_TABLES.SELF_REFERENCING_COL_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getSelfReferencingColName() {
        return selfReferencingColName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_TABLES.SELF_REFERENCING_COL_NAME
     *
     * @param selfReferencingColName the value for INFORMATION_SCHEMA.SYSTEM_TABLES.SELF_REFERENCING_COL_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setSelfReferencingColName(String selfReferencingColName) {
        this.selfReferencingColName = selfReferencingColName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_TABLES.REF_GENERATION
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_TABLES.REF_GENERATION
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getRefGeneration() {
        return refGeneration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_TABLES.REF_GENERATION
     *
     * @param refGeneration the value for INFORMATION_SCHEMA.SYSTEM_TABLES.REF_GENERATION
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setRefGeneration(String refGeneration) {
        this.refGeneration = refGeneration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_TABLES.HSQLDB_TYPE
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_TABLES.HSQLDB_TYPE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getHsqldbType() {
        return hsqldbType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_TABLES.HSQLDB_TYPE
     *
     * @param hsqldbType the value for INFORMATION_SCHEMA.SYSTEM_TABLES.HSQLDB_TYPE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setHsqldbType(String hsqldbType) {
        this.hsqldbType = hsqldbType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_TABLES.READ_ONLY
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_TABLES.READ_ONLY
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public Boolean getReadOnly() {
        return readOnly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_TABLES.READ_ONLY
     *
     * @param readOnly the value for INFORMATION_SCHEMA.SYSTEM_TABLES.READ_ONLY
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setReadOnly(Boolean readOnly) {
        this.readOnly = readOnly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.SYSTEM_TABLES.COMMIT_ACTION
     *
     * @return the value of INFORMATION_SCHEMA.SYSTEM_TABLES.COMMIT_ACTION
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getCommitAction() {
        return commitAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.SYSTEM_TABLES.COMMIT_ACTION
     *
     * @param commitAction the value for INFORMATION_SCHEMA.SYSTEM_TABLES.COMMIT_ACTION
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setCommitAction(String commitAction) {
        this.commitAction = commitAction;
    }
}