package com.pratz.dao.table.model;

public class TriggeredUpdateColumns {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.TRIGGERED_UPDATE_COLUMNS.TRIGGER_CATALOG
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String triggerCatalog;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.TRIGGERED_UPDATE_COLUMNS.TRIGGER_SCHEMA
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String triggerSchema;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.TRIGGERED_UPDATE_COLUMNS.TRIGGER_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String triggerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.TRIGGERED_UPDATE_COLUMNS.EVENT_OBJECT_CATALOG
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String eventObjectCatalog;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.TRIGGERED_UPDATE_COLUMNS.EVENT_OBJECT_SCHEMA
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String eventObjectSchema;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.TRIGGERED_UPDATE_COLUMNS.EVENT_OBJECT_TABLE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String eventObjectTable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.TRIGGERED_UPDATE_COLUMNS.EVENT_OBJECT_COLUMN
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String eventObjectColumn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.TRIGGERED_UPDATE_COLUMNS.TRIGGER_CATALOG
     *
     * @return the value of INFORMATION_SCHEMA.TRIGGERED_UPDATE_COLUMNS.TRIGGER_CATALOG
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getTriggerCatalog() {
        return triggerCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.TRIGGERED_UPDATE_COLUMNS.TRIGGER_CATALOG
     *
     * @param triggerCatalog the value for INFORMATION_SCHEMA.TRIGGERED_UPDATE_COLUMNS.TRIGGER_CATALOG
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setTriggerCatalog(String triggerCatalog) {
        this.triggerCatalog = triggerCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.TRIGGERED_UPDATE_COLUMNS.TRIGGER_SCHEMA
     *
     * @return the value of INFORMATION_SCHEMA.TRIGGERED_UPDATE_COLUMNS.TRIGGER_SCHEMA
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getTriggerSchema() {
        return triggerSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.TRIGGERED_UPDATE_COLUMNS.TRIGGER_SCHEMA
     *
     * @param triggerSchema the value for INFORMATION_SCHEMA.TRIGGERED_UPDATE_COLUMNS.TRIGGER_SCHEMA
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setTriggerSchema(String triggerSchema) {
        this.triggerSchema = triggerSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.TRIGGERED_UPDATE_COLUMNS.TRIGGER_NAME
     *
     * @return the value of INFORMATION_SCHEMA.TRIGGERED_UPDATE_COLUMNS.TRIGGER_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getTriggerName() {
        return triggerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.TRIGGERED_UPDATE_COLUMNS.TRIGGER_NAME
     *
     * @param triggerName the value for INFORMATION_SCHEMA.TRIGGERED_UPDATE_COLUMNS.TRIGGER_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setTriggerName(String triggerName) {
        this.triggerName = triggerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.TRIGGERED_UPDATE_COLUMNS.EVENT_OBJECT_CATALOG
     *
     * @return the value of INFORMATION_SCHEMA.TRIGGERED_UPDATE_COLUMNS.EVENT_OBJECT_CATALOG
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getEventObjectCatalog() {
        return eventObjectCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.TRIGGERED_UPDATE_COLUMNS.EVENT_OBJECT_CATALOG
     *
     * @param eventObjectCatalog the value for INFORMATION_SCHEMA.TRIGGERED_UPDATE_COLUMNS.EVENT_OBJECT_CATALOG
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setEventObjectCatalog(String eventObjectCatalog) {
        this.eventObjectCatalog = eventObjectCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.TRIGGERED_UPDATE_COLUMNS.EVENT_OBJECT_SCHEMA
     *
     * @return the value of INFORMATION_SCHEMA.TRIGGERED_UPDATE_COLUMNS.EVENT_OBJECT_SCHEMA
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getEventObjectSchema() {
        return eventObjectSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.TRIGGERED_UPDATE_COLUMNS.EVENT_OBJECT_SCHEMA
     *
     * @param eventObjectSchema the value for INFORMATION_SCHEMA.TRIGGERED_UPDATE_COLUMNS.EVENT_OBJECT_SCHEMA
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setEventObjectSchema(String eventObjectSchema) {
        this.eventObjectSchema = eventObjectSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.TRIGGERED_UPDATE_COLUMNS.EVENT_OBJECT_TABLE
     *
     * @return the value of INFORMATION_SCHEMA.TRIGGERED_UPDATE_COLUMNS.EVENT_OBJECT_TABLE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getEventObjectTable() {
        return eventObjectTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.TRIGGERED_UPDATE_COLUMNS.EVENT_OBJECT_TABLE
     *
     * @param eventObjectTable the value for INFORMATION_SCHEMA.TRIGGERED_UPDATE_COLUMNS.EVENT_OBJECT_TABLE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setEventObjectTable(String eventObjectTable) {
        this.eventObjectTable = eventObjectTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.TRIGGERED_UPDATE_COLUMNS.EVENT_OBJECT_COLUMN
     *
     * @return the value of INFORMATION_SCHEMA.TRIGGERED_UPDATE_COLUMNS.EVENT_OBJECT_COLUMN
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getEventObjectColumn() {
        return eventObjectColumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.TRIGGERED_UPDATE_COLUMNS.EVENT_OBJECT_COLUMN
     *
     * @param eventObjectColumn the value for INFORMATION_SCHEMA.TRIGGERED_UPDATE_COLUMNS.EVENT_OBJECT_COLUMN
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setEventObjectColumn(String eventObjectColumn) {
        this.eventObjectColumn = eventObjectColumn;
    }
}