package com.pratz.dao.table.model;

public class UserDefinedTypes {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.USER_DEFINED_TYPE_CATALOG
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String userDefinedTypeCatalog;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.USER_DEFINED_TYPE_SCHEMA
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String userDefinedTypeSchema;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.USER_DEFINED_TYPE_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String userDefinedTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.USER_DEFINED_TYPE_CATEGORY
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String userDefinedTypeCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.IS_INSTANTIABLE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String isInstantiable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.IS_FINAL
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String isFinal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.ORDERING_FORM
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String orderingForm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.ORDERING_CATEGORY
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String orderingCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.ORDERING_ROUTINE_CATALOG
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String orderingRoutineCatalog;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.ORDERING_ROUTINE_SCHEMA
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String orderingRoutineSchema;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.ORDERING_ROUTINE_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String orderingRoutineName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.REFERENCE_TYPE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String referenceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.DATA_TYPE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String dataType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.CHARACTER_MAXIMUM_LENGTH
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private Long characterMaximumLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.CHARACTER_OCTET_LENGTH
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private Long characterOctetLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.CHARACTER_SET_CATALOG
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String characterSetCatalog;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.CHARACTER_SET_SCHEMA
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String characterSetSchema;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.CHARACTER_SET_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String characterSetName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.COLLATION_CATALOG
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String collationCatalog;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.COLLATION_SCHEMA
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String collationSchema;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.COLLATION_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String collationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.NUMERIC_PRECISION
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private Long numericPrecision;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.NUMERIC_PRECISION_RADIX
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private Long numericPrecisionRadix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.NUMERIC_SCALE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private Long numericScale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.DATETIME_PRECISION
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private Long datetimePrecision;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.INTERVAL_TYPE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String intervalType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.INTERVAL_PRECISION
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private Long intervalPrecision;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.SOURCE_DTD_IDENTIFIER
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String sourceDtdIdentifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.REF_DTD_IDENTIFIER
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String refDtdIdentifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.DECLARED_DATA_TYPE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String declaredDataType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.DECLARED_NUMERIC_PRECISION
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private Long declaredNumericPrecision;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.DECLARED_NUMERIC_SCALE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private Long declaredNumericScale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.MAXIMUM_CARDINALITY
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private Long maximumCardinality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.EXTERNAL_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String externalName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.EXTERNAL_LANGUAGE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String externalLanguage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.JAVA_INTERFACE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    private String javaInterface;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.USER_DEFINED_TYPE_CATALOG
     *
     * @return the value of INFORMATION_SCHEMA.USER_DEFINED_TYPES.USER_DEFINED_TYPE_CATALOG
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getUserDefinedTypeCatalog() {
        return userDefinedTypeCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.USER_DEFINED_TYPE_CATALOG
     *
     * @param userDefinedTypeCatalog the value for INFORMATION_SCHEMA.USER_DEFINED_TYPES.USER_DEFINED_TYPE_CATALOG
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setUserDefinedTypeCatalog(String userDefinedTypeCatalog) {
        this.userDefinedTypeCatalog = userDefinedTypeCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.USER_DEFINED_TYPE_SCHEMA
     *
     * @return the value of INFORMATION_SCHEMA.USER_DEFINED_TYPES.USER_DEFINED_TYPE_SCHEMA
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getUserDefinedTypeSchema() {
        return userDefinedTypeSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.USER_DEFINED_TYPE_SCHEMA
     *
     * @param userDefinedTypeSchema the value for INFORMATION_SCHEMA.USER_DEFINED_TYPES.USER_DEFINED_TYPE_SCHEMA
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setUserDefinedTypeSchema(String userDefinedTypeSchema) {
        this.userDefinedTypeSchema = userDefinedTypeSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.USER_DEFINED_TYPE_NAME
     *
     * @return the value of INFORMATION_SCHEMA.USER_DEFINED_TYPES.USER_DEFINED_TYPE_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getUserDefinedTypeName() {
        return userDefinedTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.USER_DEFINED_TYPE_NAME
     *
     * @param userDefinedTypeName the value for INFORMATION_SCHEMA.USER_DEFINED_TYPES.USER_DEFINED_TYPE_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setUserDefinedTypeName(String userDefinedTypeName) {
        this.userDefinedTypeName = userDefinedTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.USER_DEFINED_TYPE_CATEGORY
     *
     * @return the value of INFORMATION_SCHEMA.USER_DEFINED_TYPES.USER_DEFINED_TYPE_CATEGORY
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getUserDefinedTypeCategory() {
        return userDefinedTypeCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.USER_DEFINED_TYPE_CATEGORY
     *
     * @param userDefinedTypeCategory the value for INFORMATION_SCHEMA.USER_DEFINED_TYPES.USER_DEFINED_TYPE_CATEGORY
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setUserDefinedTypeCategory(String userDefinedTypeCategory) {
        this.userDefinedTypeCategory = userDefinedTypeCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.IS_INSTANTIABLE
     *
     * @return the value of INFORMATION_SCHEMA.USER_DEFINED_TYPES.IS_INSTANTIABLE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getIsInstantiable() {
        return isInstantiable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.IS_INSTANTIABLE
     *
     * @param isInstantiable the value for INFORMATION_SCHEMA.USER_DEFINED_TYPES.IS_INSTANTIABLE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setIsInstantiable(String isInstantiable) {
        this.isInstantiable = isInstantiable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.IS_FINAL
     *
     * @return the value of INFORMATION_SCHEMA.USER_DEFINED_TYPES.IS_FINAL
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getIsFinal() {
        return isFinal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.IS_FINAL
     *
     * @param isFinal the value for INFORMATION_SCHEMA.USER_DEFINED_TYPES.IS_FINAL
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setIsFinal(String isFinal) {
        this.isFinal = isFinal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.ORDERING_FORM
     *
     * @return the value of INFORMATION_SCHEMA.USER_DEFINED_TYPES.ORDERING_FORM
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getOrderingForm() {
        return orderingForm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.ORDERING_FORM
     *
     * @param orderingForm the value for INFORMATION_SCHEMA.USER_DEFINED_TYPES.ORDERING_FORM
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setOrderingForm(String orderingForm) {
        this.orderingForm = orderingForm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.ORDERING_CATEGORY
     *
     * @return the value of INFORMATION_SCHEMA.USER_DEFINED_TYPES.ORDERING_CATEGORY
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getOrderingCategory() {
        return orderingCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.ORDERING_CATEGORY
     *
     * @param orderingCategory the value for INFORMATION_SCHEMA.USER_DEFINED_TYPES.ORDERING_CATEGORY
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setOrderingCategory(String orderingCategory) {
        this.orderingCategory = orderingCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.ORDERING_ROUTINE_CATALOG
     *
     * @return the value of INFORMATION_SCHEMA.USER_DEFINED_TYPES.ORDERING_ROUTINE_CATALOG
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getOrderingRoutineCatalog() {
        return orderingRoutineCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.ORDERING_ROUTINE_CATALOG
     *
     * @param orderingRoutineCatalog the value for INFORMATION_SCHEMA.USER_DEFINED_TYPES.ORDERING_ROUTINE_CATALOG
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setOrderingRoutineCatalog(String orderingRoutineCatalog) {
        this.orderingRoutineCatalog = orderingRoutineCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.ORDERING_ROUTINE_SCHEMA
     *
     * @return the value of INFORMATION_SCHEMA.USER_DEFINED_TYPES.ORDERING_ROUTINE_SCHEMA
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getOrderingRoutineSchema() {
        return orderingRoutineSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.ORDERING_ROUTINE_SCHEMA
     *
     * @param orderingRoutineSchema the value for INFORMATION_SCHEMA.USER_DEFINED_TYPES.ORDERING_ROUTINE_SCHEMA
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setOrderingRoutineSchema(String orderingRoutineSchema) {
        this.orderingRoutineSchema = orderingRoutineSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.ORDERING_ROUTINE_NAME
     *
     * @return the value of INFORMATION_SCHEMA.USER_DEFINED_TYPES.ORDERING_ROUTINE_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getOrderingRoutineName() {
        return orderingRoutineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.ORDERING_ROUTINE_NAME
     *
     * @param orderingRoutineName the value for INFORMATION_SCHEMA.USER_DEFINED_TYPES.ORDERING_ROUTINE_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setOrderingRoutineName(String orderingRoutineName) {
        this.orderingRoutineName = orderingRoutineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.REFERENCE_TYPE
     *
     * @return the value of INFORMATION_SCHEMA.USER_DEFINED_TYPES.REFERENCE_TYPE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getReferenceType() {
        return referenceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.REFERENCE_TYPE
     *
     * @param referenceType the value for INFORMATION_SCHEMA.USER_DEFINED_TYPES.REFERENCE_TYPE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setReferenceType(String referenceType) {
        this.referenceType = referenceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.DATA_TYPE
     *
     * @return the value of INFORMATION_SCHEMA.USER_DEFINED_TYPES.DATA_TYPE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.DATA_TYPE
     *
     * @param dataType the value for INFORMATION_SCHEMA.USER_DEFINED_TYPES.DATA_TYPE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setDataType(String dataType) {
        this.dataType = dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.CHARACTER_MAXIMUM_LENGTH
     *
     * @return the value of INFORMATION_SCHEMA.USER_DEFINED_TYPES.CHARACTER_MAXIMUM_LENGTH
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public Long getCharacterMaximumLength() {
        return characterMaximumLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.CHARACTER_MAXIMUM_LENGTH
     *
     * @param characterMaximumLength the value for INFORMATION_SCHEMA.USER_DEFINED_TYPES.CHARACTER_MAXIMUM_LENGTH
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setCharacterMaximumLength(Long characterMaximumLength) {
        this.characterMaximumLength = characterMaximumLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.CHARACTER_OCTET_LENGTH
     *
     * @return the value of INFORMATION_SCHEMA.USER_DEFINED_TYPES.CHARACTER_OCTET_LENGTH
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public Long getCharacterOctetLength() {
        return characterOctetLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.CHARACTER_OCTET_LENGTH
     *
     * @param characterOctetLength the value for INFORMATION_SCHEMA.USER_DEFINED_TYPES.CHARACTER_OCTET_LENGTH
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setCharacterOctetLength(Long characterOctetLength) {
        this.characterOctetLength = characterOctetLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.CHARACTER_SET_CATALOG
     *
     * @return the value of INFORMATION_SCHEMA.USER_DEFINED_TYPES.CHARACTER_SET_CATALOG
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getCharacterSetCatalog() {
        return characterSetCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.CHARACTER_SET_CATALOG
     *
     * @param characterSetCatalog the value for INFORMATION_SCHEMA.USER_DEFINED_TYPES.CHARACTER_SET_CATALOG
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setCharacterSetCatalog(String characterSetCatalog) {
        this.characterSetCatalog = characterSetCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.CHARACTER_SET_SCHEMA
     *
     * @return the value of INFORMATION_SCHEMA.USER_DEFINED_TYPES.CHARACTER_SET_SCHEMA
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getCharacterSetSchema() {
        return characterSetSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.CHARACTER_SET_SCHEMA
     *
     * @param characterSetSchema the value for INFORMATION_SCHEMA.USER_DEFINED_TYPES.CHARACTER_SET_SCHEMA
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setCharacterSetSchema(String characterSetSchema) {
        this.characterSetSchema = characterSetSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.CHARACTER_SET_NAME
     *
     * @return the value of INFORMATION_SCHEMA.USER_DEFINED_TYPES.CHARACTER_SET_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getCharacterSetName() {
        return characterSetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.CHARACTER_SET_NAME
     *
     * @param characterSetName the value for INFORMATION_SCHEMA.USER_DEFINED_TYPES.CHARACTER_SET_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setCharacterSetName(String characterSetName) {
        this.characterSetName = characterSetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.COLLATION_CATALOG
     *
     * @return the value of INFORMATION_SCHEMA.USER_DEFINED_TYPES.COLLATION_CATALOG
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getCollationCatalog() {
        return collationCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.COLLATION_CATALOG
     *
     * @param collationCatalog the value for INFORMATION_SCHEMA.USER_DEFINED_TYPES.COLLATION_CATALOG
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setCollationCatalog(String collationCatalog) {
        this.collationCatalog = collationCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.COLLATION_SCHEMA
     *
     * @return the value of INFORMATION_SCHEMA.USER_DEFINED_TYPES.COLLATION_SCHEMA
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getCollationSchema() {
        return collationSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.COLLATION_SCHEMA
     *
     * @param collationSchema the value for INFORMATION_SCHEMA.USER_DEFINED_TYPES.COLLATION_SCHEMA
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setCollationSchema(String collationSchema) {
        this.collationSchema = collationSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.COLLATION_NAME
     *
     * @return the value of INFORMATION_SCHEMA.USER_DEFINED_TYPES.COLLATION_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getCollationName() {
        return collationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.COLLATION_NAME
     *
     * @param collationName the value for INFORMATION_SCHEMA.USER_DEFINED_TYPES.COLLATION_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setCollationName(String collationName) {
        this.collationName = collationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.NUMERIC_PRECISION
     *
     * @return the value of INFORMATION_SCHEMA.USER_DEFINED_TYPES.NUMERIC_PRECISION
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public Long getNumericPrecision() {
        return numericPrecision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.NUMERIC_PRECISION
     *
     * @param numericPrecision the value for INFORMATION_SCHEMA.USER_DEFINED_TYPES.NUMERIC_PRECISION
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setNumericPrecision(Long numericPrecision) {
        this.numericPrecision = numericPrecision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.NUMERIC_PRECISION_RADIX
     *
     * @return the value of INFORMATION_SCHEMA.USER_DEFINED_TYPES.NUMERIC_PRECISION_RADIX
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public Long getNumericPrecisionRadix() {
        return numericPrecisionRadix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.NUMERIC_PRECISION_RADIX
     *
     * @param numericPrecisionRadix the value for INFORMATION_SCHEMA.USER_DEFINED_TYPES.NUMERIC_PRECISION_RADIX
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setNumericPrecisionRadix(Long numericPrecisionRadix) {
        this.numericPrecisionRadix = numericPrecisionRadix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.NUMERIC_SCALE
     *
     * @return the value of INFORMATION_SCHEMA.USER_DEFINED_TYPES.NUMERIC_SCALE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public Long getNumericScale() {
        return numericScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.NUMERIC_SCALE
     *
     * @param numericScale the value for INFORMATION_SCHEMA.USER_DEFINED_TYPES.NUMERIC_SCALE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setNumericScale(Long numericScale) {
        this.numericScale = numericScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.DATETIME_PRECISION
     *
     * @return the value of INFORMATION_SCHEMA.USER_DEFINED_TYPES.DATETIME_PRECISION
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public Long getDatetimePrecision() {
        return datetimePrecision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.DATETIME_PRECISION
     *
     * @param datetimePrecision the value for INFORMATION_SCHEMA.USER_DEFINED_TYPES.DATETIME_PRECISION
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setDatetimePrecision(Long datetimePrecision) {
        this.datetimePrecision = datetimePrecision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.INTERVAL_TYPE
     *
     * @return the value of INFORMATION_SCHEMA.USER_DEFINED_TYPES.INTERVAL_TYPE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getIntervalType() {
        return intervalType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.INTERVAL_TYPE
     *
     * @param intervalType the value for INFORMATION_SCHEMA.USER_DEFINED_TYPES.INTERVAL_TYPE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setIntervalType(String intervalType) {
        this.intervalType = intervalType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.INTERVAL_PRECISION
     *
     * @return the value of INFORMATION_SCHEMA.USER_DEFINED_TYPES.INTERVAL_PRECISION
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public Long getIntervalPrecision() {
        return intervalPrecision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.INTERVAL_PRECISION
     *
     * @param intervalPrecision the value for INFORMATION_SCHEMA.USER_DEFINED_TYPES.INTERVAL_PRECISION
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setIntervalPrecision(Long intervalPrecision) {
        this.intervalPrecision = intervalPrecision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.SOURCE_DTD_IDENTIFIER
     *
     * @return the value of INFORMATION_SCHEMA.USER_DEFINED_TYPES.SOURCE_DTD_IDENTIFIER
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getSourceDtdIdentifier() {
        return sourceDtdIdentifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.SOURCE_DTD_IDENTIFIER
     *
     * @param sourceDtdIdentifier the value for INFORMATION_SCHEMA.USER_DEFINED_TYPES.SOURCE_DTD_IDENTIFIER
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setSourceDtdIdentifier(String sourceDtdIdentifier) {
        this.sourceDtdIdentifier = sourceDtdIdentifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.REF_DTD_IDENTIFIER
     *
     * @return the value of INFORMATION_SCHEMA.USER_DEFINED_TYPES.REF_DTD_IDENTIFIER
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getRefDtdIdentifier() {
        return refDtdIdentifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.REF_DTD_IDENTIFIER
     *
     * @param refDtdIdentifier the value for INFORMATION_SCHEMA.USER_DEFINED_TYPES.REF_DTD_IDENTIFIER
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setRefDtdIdentifier(String refDtdIdentifier) {
        this.refDtdIdentifier = refDtdIdentifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.DECLARED_DATA_TYPE
     *
     * @return the value of INFORMATION_SCHEMA.USER_DEFINED_TYPES.DECLARED_DATA_TYPE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getDeclaredDataType() {
        return declaredDataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.DECLARED_DATA_TYPE
     *
     * @param declaredDataType the value for INFORMATION_SCHEMA.USER_DEFINED_TYPES.DECLARED_DATA_TYPE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setDeclaredDataType(String declaredDataType) {
        this.declaredDataType = declaredDataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.DECLARED_NUMERIC_PRECISION
     *
     * @return the value of INFORMATION_SCHEMA.USER_DEFINED_TYPES.DECLARED_NUMERIC_PRECISION
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public Long getDeclaredNumericPrecision() {
        return declaredNumericPrecision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.DECLARED_NUMERIC_PRECISION
     *
     * @param declaredNumericPrecision the value for INFORMATION_SCHEMA.USER_DEFINED_TYPES.DECLARED_NUMERIC_PRECISION
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setDeclaredNumericPrecision(Long declaredNumericPrecision) {
        this.declaredNumericPrecision = declaredNumericPrecision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.DECLARED_NUMERIC_SCALE
     *
     * @return the value of INFORMATION_SCHEMA.USER_DEFINED_TYPES.DECLARED_NUMERIC_SCALE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public Long getDeclaredNumericScale() {
        return declaredNumericScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.DECLARED_NUMERIC_SCALE
     *
     * @param declaredNumericScale the value for INFORMATION_SCHEMA.USER_DEFINED_TYPES.DECLARED_NUMERIC_SCALE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setDeclaredNumericScale(Long declaredNumericScale) {
        this.declaredNumericScale = declaredNumericScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.MAXIMUM_CARDINALITY
     *
     * @return the value of INFORMATION_SCHEMA.USER_DEFINED_TYPES.MAXIMUM_CARDINALITY
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public Long getMaximumCardinality() {
        return maximumCardinality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.MAXIMUM_CARDINALITY
     *
     * @param maximumCardinality the value for INFORMATION_SCHEMA.USER_DEFINED_TYPES.MAXIMUM_CARDINALITY
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setMaximumCardinality(Long maximumCardinality) {
        this.maximumCardinality = maximumCardinality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.EXTERNAL_NAME
     *
     * @return the value of INFORMATION_SCHEMA.USER_DEFINED_TYPES.EXTERNAL_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getExternalName() {
        return externalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.EXTERNAL_NAME
     *
     * @param externalName the value for INFORMATION_SCHEMA.USER_DEFINED_TYPES.EXTERNAL_NAME
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setExternalName(String externalName) {
        this.externalName = externalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.EXTERNAL_LANGUAGE
     *
     * @return the value of INFORMATION_SCHEMA.USER_DEFINED_TYPES.EXTERNAL_LANGUAGE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getExternalLanguage() {
        return externalLanguage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.EXTERNAL_LANGUAGE
     *
     * @param externalLanguage the value for INFORMATION_SCHEMA.USER_DEFINED_TYPES.EXTERNAL_LANGUAGE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setExternalLanguage(String externalLanguage) {
        this.externalLanguage = externalLanguage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.JAVA_INTERFACE
     *
     * @return the value of INFORMATION_SCHEMA.USER_DEFINED_TYPES.JAVA_INTERFACE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getJavaInterface() {
        return javaInterface;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION_SCHEMA.USER_DEFINED_TYPES.JAVA_INTERFACE
     *
     * @param javaInterface the value for INFORMATION_SCHEMA.USER_DEFINED_TYPES.JAVA_INTERFACE
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setJavaInterface(String javaInterface) {
        this.javaInterface = javaInterface;
    }
}