package com.pratz.dao.table.model;

import java.util.ArrayList;
import java.util.List;

public class ViewsCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table INFORMATION_SCHEMA.VIEWS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table INFORMATION_SCHEMA.VIEWS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table INFORMATION_SCHEMA.VIEWS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.VIEWS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public ViewsCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.VIEWS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.VIEWS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.VIEWS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.VIEWS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.VIEWS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.VIEWS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.VIEWS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.VIEWS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.VIEWS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORMATION_SCHEMA.VIEWS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table INFORMATION_SCHEMA.VIEWS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTableCatalogIsNull() {
            addCriterion("TABLE_CATALOG is null");
            return (Criteria) this;
        }

        public Criteria andTableCatalogIsNotNull() {
            addCriterion("TABLE_CATALOG is not null");
            return (Criteria) this;
        }

        public Criteria andTableCatalogEqualTo(String value) {
            addCriterion("TABLE_CATALOG =", value, "tableCatalog");
            return (Criteria) this;
        }

        public Criteria andTableCatalogNotEqualTo(String value) {
            addCriterion("TABLE_CATALOG <>", value, "tableCatalog");
            return (Criteria) this;
        }

        public Criteria andTableCatalogGreaterThan(String value) {
            addCriterion("TABLE_CATALOG >", value, "tableCatalog");
            return (Criteria) this;
        }

        public Criteria andTableCatalogGreaterThanOrEqualTo(String value) {
            addCriterion("TABLE_CATALOG >=", value, "tableCatalog");
            return (Criteria) this;
        }

        public Criteria andTableCatalogLessThan(String value) {
            addCriterion("TABLE_CATALOG <", value, "tableCatalog");
            return (Criteria) this;
        }

        public Criteria andTableCatalogLessThanOrEqualTo(String value) {
            addCriterion("TABLE_CATALOG <=", value, "tableCatalog");
            return (Criteria) this;
        }

        public Criteria andTableCatalogLike(String value) {
            addCriterion("TABLE_CATALOG like", value, "tableCatalog");
            return (Criteria) this;
        }

        public Criteria andTableCatalogNotLike(String value) {
            addCriterion("TABLE_CATALOG not like", value, "tableCatalog");
            return (Criteria) this;
        }

        public Criteria andTableCatalogIn(List<String> values) {
            addCriterion("TABLE_CATALOG in", values, "tableCatalog");
            return (Criteria) this;
        }

        public Criteria andTableCatalogNotIn(List<String> values) {
            addCriterion("TABLE_CATALOG not in", values, "tableCatalog");
            return (Criteria) this;
        }

        public Criteria andTableCatalogBetween(String value1, String value2) {
            addCriterion("TABLE_CATALOG between", value1, value2, "tableCatalog");
            return (Criteria) this;
        }

        public Criteria andTableCatalogNotBetween(String value1, String value2) {
            addCriterion("TABLE_CATALOG not between", value1, value2, "tableCatalog");
            return (Criteria) this;
        }

        public Criteria andTableSchemaIsNull() {
            addCriterion("TABLE_SCHEMA is null");
            return (Criteria) this;
        }

        public Criteria andTableSchemaIsNotNull() {
            addCriterion("TABLE_SCHEMA is not null");
            return (Criteria) this;
        }

        public Criteria andTableSchemaEqualTo(String value) {
            addCriterion("TABLE_SCHEMA =", value, "tableSchema");
            return (Criteria) this;
        }

        public Criteria andTableSchemaNotEqualTo(String value) {
            addCriterion("TABLE_SCHEMA <>", value, "tableSchema");
            return (Criteria) this;
        }

        public Criteria andTableSchemaGreaterThan(String value) {
            addCriterion("TABLE_SCHEMA >", value, "tableSchema");
            return (Criteria) this;
        }

        public Criteria andTableSchemaGreaterThanOrEqualTo(String value) {
            addCriterion("TABLE_SCHEMA >=", value, "tableSchema");
            return (Criteria) this;
        }

        public Criteria andTableSchemaLessThan(String value) {
            addCriterion("TABLE_SCHEMA <", value, "tableSchema");
            return (Criteria) this;
        }

        public Criteria andTableSchemaLessThanOrEqualTo(String value) {
            addCriterion("TABLE_SCHEMA <=", value, "tableSchema");
            return (Criteria) this;
        }

        public Criteria andTableSchemaLike(String value) {
            addCriterion("TABLE_SCHEMA like", value, "tableSchema");
            return (Criteria) this;
        }

        public Criteria andTableSchemaNotLike(String value) {
            addCriterion("TABLE_SCHEMA not like", value, "tableSchema");
            return (Criteria) this;
        }

        public Criteria andTableSchemaIn(List<String> values) {
            addCriterion("TABLE_SCHEMA in", values, "tableSchema");
            return (Criteria) this;
        }

        public Criteria andTableSchemaNotIn(List<String> values) {
            addCriterion("TABLE_SCHEMA not in", values, "tableSchema");
            return (Criteria) this;
        }

        public Criteria andTableSchemaBetween(String value1, String value2) {
            addCriterion("TABLE_SCHEMA between", value1, value2, "tableSchema");
            return (Criteria) this;
        }

        public Criteria andTableSchemaNotBetween(String value1, String value2) {
            addCriterion("TABLE_SCHEMA not between", value1, value2, "tableSchema");
            return (Criteria) this;
        }

        public Criteria andTableNameIsNull() {
            addCriterion("TABLE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andTableNameIsNotNull() {
            addCriterion("TABLE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andTableNameEqualTo(String value) {
            addCriterion("TABLE_NAME =", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameNotEqualTo(String value) {
            addCriterion("TABLE_NAME <>", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameGreaterThan(String value) {
            addCriterion("TABLE_NAME >", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameGreaterThanOrEqualTo(String value) {
            addCriterion("TABLE_NAME >=", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameLessThan(String value) {
            addCriterion("TABLE_NAME <", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameLessThanOrEqualTo(String value) {
            addCriterion("TABLE_NAME <=", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameLike(String value) {
            addCriterion("TABLE_NAME like", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameNotLike(String value) {
            addCriterion("TABLE_NAME not like", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameIn(List<String> values) {
            addCriterion("TABLE_NAME in", values, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameNotIn(List<String> values) {
            addCriterion("TABLE_NAME not in", values, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameBetween(String value1, String value2) {
            addCriterion("TABLE_NAME between", value1, value2, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameNotBetween(String value1, String value2) {
            addCriterion("TABLE_NAME not between", value1, value2, "tableName");
            return (Criteria) this;
        }

        public Criteria andViewDefinitionIsNull() {
            addCriterion("VIEW_DEFINITION is null");
            return (Criteria) this;
        }

        public Criteria andViewDefinitionIsNotNull() {
            addCriterion("VIEW_DEFINITION is not null");
            return (Criteria) this;
        }

        public Criteria andViewDefinitionEqualTo(String value) {
            addCriterion("VIEW_DEFINITION =", value, "viewDefinition");
            return (Criteria) this;
        }

        public Criteria andViewDefinitionNotEqualTo(String value) {
            addCriterion("VIEW_DEFINITION <>", value, "viewDefinition");
            return (Criteria) this;
        }

        public Criteria andViewDefinitionGreaterThan(String value) {
            addCriterion("VIEW_DEFINITION >", value, "viewDefinition");
            return (Criteria) this;
        }

        public Criteria andViewDefinitionGreaterThanOrEqualTo(String value) {
            addCriterion("VIEW_DEFINITION >=", value, "viewDefinition");
            return (Criteria) this;
        }

        public Criteria andViewDefinitionLessThan(String value) {
            addCriterion("VIEW_DEFINITION <", value, "viewDefinition");
            return (Criteria) this;
        }

        public Criteria andViewDefinitionLessThanOrEqualTo(String value) {
            addCriterion("VIEW_DEFINITION <=", value, "viewDefinition");
            return (Criteria) this;
        }

        public Criteria andViewDefinitionLike(String value) {
            addCriterion("VIEW_DEFINITION like", value, "viewDefinition");
            return (Criteria) this;
        }

        public Criteria andViewDefinitionNotLike(String value) {
            addCriterion("VIEW_DEFINITION not like", value, "viewDefinition");
            return (Criteria) this;
        }

        public Criteria andViewDefinitionIn(List<String> values) {
            addCriterion("VIEW_DEFINITION in", values, "viewDefinition");
            return (Criteria) this;
        }

        public Criteria andViewDefinitionNotIn(List<String> values) {
            addCriterion("VIEW_DEFINITION not in", values, "viewDefinition");
            return (Criteria) this;
        }

        public Criteria andViewDefinitionBetween(String value1, String value2) {
            addCriterion("VIEW_DEFINITION between", value1, value2, "viewDefinition");
            return (Criteria) this;
        }

        public Criteria andViewDefinitionNotBetween(String value1, String value2) {
            addCriterion("VIEW_DEFINITION not between", value1, value2, "viewDefinition");
            return (Criteria) this;
        }

        public Criteria andCheckOptionIsNull() {
            addCriterion("CHECK_OPTION is null");
            return (Criteria) this;
        }

        public Criteria andCheckOptionIsNotNull() {
            addCriterion("CHECK_OPTION is not null");
            return (Criteria) this;
        }

        public Criteria andCheckOptionEqualTo(String value) {
            addCriterion("CHECK_OPTION =", value, "checkOption");
            return (Criteria) this;
        }

        public Criteria andCheckOptionNotEqualTo(String value) {
            addCriterion("CHECK_OPTION <>", value, "checkOption");
            return (Criteria) this;
        }

        public Criteria andCheckOptionGreaterThan(String value) {
            addCriterion("CHECK_OPTION >", value, "checkOption");
            return (Criteria) this;
        }

        public Criteria andCheckOptionGreaterThanOrEqualTo(String value) {
            addCriterion("CHECK_OPTION >=", value, "checkOption");
            return (Criteria) this;
        }

        public Criteria andCheckOptionLessThan(String value) {
            addCriterion("CHECK_OPTION <", value, "checkOption");
            return (Criteria) this;
        }

        public Criteria andCheckOptionLessThanOrEqualTo(String value) {
            addCriterion("CHECK_OPTION <=", value, "checkOption");
            return (Criteria) this;
        }

        public Criteria andCheckOptionLike(String value) {
            addCriterion("CHECK_OPTION like", value, "checkOption");
            return (Criteria) this;
        }

        public Criteria andCheckOptionNotLike(String value) {
            addCriterion("CHECK_OPTION not like", value, "checkOption");
            return (Criteria) this;
        }

        public Criteria andCheckOptionIn(List<String> values) {
            addCriterion("CHECK_OPTION in", values, "checkOption");
            return (Criteria) this;
        }

        public Criteria andCheckOptionNotIn(List<String> values) {
            addCriterion("CHECK_OPTION not in", values, "checkOption");
            return (Criteria) this;
        }

        public Criteria andCheckOptionBetween(String value1, String value2) {
            addCriterion("CHECK_OPTION between", value1, value2, "checkOption");
            return (Criteria) this;
        }

        public Criteria andCheckOptionNotBetween(String value1, String value2) {
            addCriterion("CHECK_OPTION not between", value1, value2, "checkOption");
            return (Criteria) this;
        }

        public Criteria andIsUpdatableIsNull() {
            addCriterion("IS_UPDATABLE is null");
            return (Criteria) this;
        }

        public Criteria andIsUpdatableIsNotNull() {
            addCriterion("IS_UPDATABLE is not null");
            return (Criteria) this;
        }

        public Criteria andIsUpdatableEqualTo(String value) {
            addCriterion("IS_UPDATABLE =", value, "isUpdatable");
            return (Criteria) this;
        }

        public Criteria andIsUpdatableNotEqualTo(String value) {
            addCriterion("IS_UPDATABLE <>", value, "isUpdatable");
            return (Criteria) this;
        }

        public Criteria andIsUpdatableGreaterThan(String value) {
            addCriterion("IS_UPDATABLE >", value, "isUpdatable");
            return (Criteria) this;
        }

        public Criteria andIsUpdatableGreaterThanOrEqualTo(String value) {
            addCriterion("IS_UPDATABLE >=", value, "isUpdatable");
            return (Criteria) this;
        }

        public Criteria andIsUpdatableLessThan(String value) {
            addCriterion("IS_UPDATABLE <", value, "isUpdatable");
            return (Criteria) this;
        }

        public Criteria andIsUpdatableLessThanOrEqualTo(String value) {
            addCriterion("IS_UPDATABLE <=", value, "isUpdatable");
            return (Criteria) this;
        }

        public Criteria andIsUpdatableLike(String value) {
            addCriterion("IS_UPDATABLE like", value, "isUpdatable");
            return (Criteria) this;
        }

        public Criteria andIsUpdatableNotLike(String value) {
            addCriterion("IS_UPDATABLE not like", value, "isUpdatable");
            return (Criteria) this;
        }

        public Criteria andIsUpdatableIn(List<String> values) {
            addCriterion("IS_UPDATABLE in", values, "isUpdatable");
            return (Criteria) this;
        }

        public Criteria andIsUpdatableNotIn(List<String> values) {
            addCriterion("IS_UPDATABLE not in", values, "isUpdatable");
            return (Criteria) this;
        }

        public Criteria andIsUpdatableBetween(String value1, String value2) {
            addCriterion("IS_UPDATABLE between", value1, value2, "isUpdatable");
            return (Criteria) this;
        }

        public Criteria andIsUpdatableNotBetween(String value1, String value2) {
            addCriterion("IS_UPDATABLE not between", value1, value2, "isUpdatable");
            return (Criteria) this;
        }

        public Criteria andInsertableIntoIsNull() {
            addCriterion("INSERTABLE_INTO is null");
            return (Criteria) this;
        }

        public Criteria andInsertableIntoIsNotNull() {
            addCriterion("INSERTABLE_INTO is not null");
            return (Criteria) this;
        }

        public Criteria andInsertableIntoEqualTo(String value) {
            addCriterion("INSERTABLE_INTO =", value, "insertableInto");
            return (Criteria) this;
        }

        public Criteria andInsertableIntoNotEqualTo(String value) {
            addCriterion("INSERTABLE_INTO <>", value, "insertableInto");
            return (Criteria) this;
        }

        public Criteria andInsertableIntoGreaterThan(String value) {
            addCriterion("INSERTABLE_INTO >", value, "insertableInto");
            return (Criteria) this;
        }

        public Criteria andInsertableIntoGreaterThanOrEqualTo(String value) {
            addCriterion("INSERTABLE_INTO >=", value, "insertableInto");
            return (Criteria) this;
        }

        public Criteria andInsertableIntoLessThan(String value) {
            addCriterion("INSERTABLE_INTO <", value, "insertableInto");
            return (Criteria) this;
        }

        public Criteria andInsertableIntoLessThanOrEqualTo(String value) {
            addCriterion("INSERTABLE_INTO <=", value, "insertableInto");
            return (Criteria) this;
        }

        public Criteria andInsertableIntoLike(String value) {
            addCriterion("INSERTABLE_INTO like", value, "insertableInto");
            return (Criteria) this;
        }

        public Criteria andInsertableIntoNotLike(String value) {
            addCriterion("INSERTABLE_INTO not like", value, "insertableInto");
            return (Criteria) this;
        }

        public Criteria andInsertableIntoIn(List<String> values) {
            addCriterion("INSERTABLE_INTO in", values, "insertableInto");
            return (Criteria) this;
        }

        public Criteria andInsertableIntoNotIn(List<String> values) {
            addCriterion("INSERTABLE_INTO not in", values, "insertableInto");
            return (Criteria) this;
        }

        public Criteria andInsertableIntoBetween(String value1, String value2) {
            addCriterion("INSERTABLE_INTO between", value1, value2, "insertableInto");
            return (Criteria) this;
        }

        public Criteria andInsertableIntoNotBetween(String value1, String value2) {
            addCriterion("INSERTABLE_INTO not between", value1, value2, "insertableInto");
            return (Criteria) this;
        }

        public Criteria andIsTriggerUpdatableIsNull() {
            addCriterion("IS_TRIGGER_UPDATABLE is null");
            return (Criteria) this;
        }

        public Criteria andIsTriggerUpdatableIsNotNull() {
            addCriterion("IS_TRIGGER_UPDATABLE is not null");
            return (Criteria) this;
        }

        public Criteria andIsTriggerUpdatableEqualTo(String value) {
            addCriterion("IS_TRIGGER_UPDATABLE =", value, "isTriggerUpdatable");
            return (Criteria) this;
        }

        public Criteria andIsTriggerUpdatableNotEqualTo(String value) {
            addCriterion("IS_TRIGGER_UPDATABLE <>", value, "isTriggerUpdatable");
            return (Criteria) this;
        }

        public Criteria andIsTriggerUpdatableGreaterThan(String value) {
            addCriterion("IS_TRIGGER_UPDATABLE >", value, "isTriggerUpdatable");
            return (Criteria) this;
        }

        public Criteria andIsTriggerUpdatableGreaterThanOrEqualTo(String value) {
            addCriterion("IS_TRIGGER_UPDATABLE >=", value, "isTriggerUpdatable");
            return (Criteria) this;
        }

        public Criteria andIsTriggerUpdatableLessThan(String value) {
            addCriterion("IS_TRIGGER_UPDATABLE <", value, "isTriggerUpdatable");
            return (Criteria) this;
        }

        public Criteria andIsTriggerUpdatableLessThanOrEqualTo(String value) {
            addCriterion("IS_TRIGGER_UPDATABLE <=", value, "isTriggerUpdatable");
            return (Criteria) this;
        }

        public Criteria andIsTriggerUpdatableLike(String value) {
            addCriterion("IS_TRIGGER_UPDATABLE like", value, "isTriggerUpdatable");
            return (Criteria) this;
        }

        public Criteria andIsTriggerUpdatableNotLike(String value) {
            addCriterion("IS_TRIGGER_UPDATABLE not like", value, "isTriggerUpdatable");
            return (Criteria) this;
        }

        public Criteria andIsTriggerUpdatableIn(List<String> values) {
            addCriterion("IS_TRIGGER_UPDATABLE in", values, "isTriggerUpdatable");
            return (Criteria) this;
        }

        public Criteria andIsTriggerUpdatableNotIn(List<String> values) {
            addCriterion("IS_TRIGGER_UPDATABLE not in", values, "isTriggerUpdatable");
            return (Criteria) this;
        }

        public Criteria andIsTriggerUpdatableBetween(String value1, String value2) {
            addCriterion("IS_TRIGGER_UPDATABLE between", value1, value2, "isTriggerUpdatable");
            return (Criteria) this;
        }

        public Criteria andIsTriggerUpdatableNotBetween(String value1, String value2) {
            addCriterion("IS_TRIGGER_UPDATABLE not between", value1, value2, "isTriggerUpdatable");
            return (Criteria) this;
        }

        public Criteria andIsTriggerDeletableIsNull() {
            addCriterion("IS_TRIGGER_DELETABLE is null");
            return (Criteria) this;
        }

        public Criteria andIsTriggerDeletableIsNotNull() {
            addCriterion("IS_TRIGGER_DELETABLE is not null");
            return (Criteria) this;
        }

        public Criteria andIsTriggerDeletableEqualTo(String value) {
            addCriterion("IS_TRIGGER_DELETABLE =", value, "isTriggerDeletable");
            return (Criteria) this;
        }

        public Criteria andIsTriggerDeletableNotEqualTo(String value) {
            addCriterion("IS_TRIGGER_DELETABLE <>", value, "isTriggerDeletable");
            return (Criteria) this;
        }

        public Criteria andIsTriggerDeletableGreaterThan(String value) {
            addCriterion("IS_TRIGGER_DELETABLE >", value, "isTriggerDeletable");
            return (Criteria) this;
        }

        public Criteria andIsTriggerDeletableGreaterThanOrEqualTo(String value) {
            addCriterion("IS_TRIGGER_DELETABLE >=", value, "isTriggerDeletable");
            return (Criteria) this;
        }

        public Criteria andIsTriggerDeletableLessThan(String value) {
            addCriterion("IS_TRIGGER_DELETABLE <", value, "isTriggerDeletable");
            return (Criteria) this;
        }

        public Criteria andIsTriggerDeletableLessThanOrEqualTo(String value) {
            addCriterion("IS_TRIGGER_DELETABLE <=", value, "isTriggerDeletable");
            return (Criteria) this;
        }

        public Criteria andIsTriggerDeletableLike(String value) {
            addCriterion("IS_TRIGGER_DELETABLE like", value, "isTriggerDeletable");
            return (Criteria) this;
        }

        public Criteria andIsTriggerDeletableNotLike(String value) {
            addCriterion("IS_TRIGGER_DELETABLE not like", value, "isTriggerDeletable");
            return (Criteria) this;
        }

        public Criteria andIsTriggerDeletableIn(List<String> values) {
            addCriterion("IS_TRIGGER_DELETABLE in", values, "isTriggerDeletable");
            return (Criteria) this;
        }

        public Criteria andIsTriggerDeletableNotIn(List<String> values) {
            addCriterion("IS_TRIGGER_DELETABLE not in", values, "isTriggerDeletable");
            return (Criteria) this;
        }

        public Criteria andIsTriggerDeletableBetween(String value1, String value2) {
            addCriterion("IS_TRIGGER_DELETABLE between", value1, value2, "isTriggerDeletable");
            return (Criteria) this;
        }

        public Criteria andIsTriggerDeletableNotBetween(String value1, String value2) {
            addCriterion("IS_TRIGGER_DELETABLE not between", value1, value2, "isTriggerDeletable");
            return (Criteria) this;
        }

        public Criteria andIsTriggerInsertableIntoIsNull() {
            addCriterion("IS_TRIGGER_INSERTABLE_INTO is null");
            return (Criteria) this;
        }

        public Criteria andIsTriggerInsertableIntoIsNotNull() {
            addCriterion("IS_TRIGGER_INSERTABLE_INTO is not null");
            return (Criteria) this;
        }

        public Criteria andIsTriggerInsertableIntoEqualTo(String value) {
            addCriterion("IS_TRIGGER_INSERTABLE_INTO =", value, "isTriggerInsertableInto");
            return (Criteria) this;
        }

        public Criteria andIsTriggerInsertableIntoNotEqualTo(String value) {
            addCriterion("IS_TRIGGER_INSERTABLE_INTO <>", value, "isTriggerInsertableInto");
            return (Criteria) this;
        }

        public Criteria andIsTriggerInsertableIntoGreaterThan(String value) {
            addCriterion("IS_TRIGGER_INSERTABLE_INTO >", value, "isTriggerInsertableInto");
            return (Criteria) this;
        }

        public Criteria andIsTriggerInsertableIntoGreaterThanOrEqualTo(String value) {
            addCriterion("IS_TRIGGER_INSERTABLE_INTO >=", value, "isTriggerInsertableInto");
            return (Criteria) this;
        }

        public Criteria andIsTriggerInsertableIntoLessThan(String value) {
            addCriterion("IS_TRIGGER_INSERTABLE_INTO <", value, "isTriggerInsertableInto");
            return (Criteria) this;
        }

        public Criteria andIsTriggerInsertableIntoLessThanOrEqualTo(String value) {
            addCriterion("IS_TRIGGER_INSERTABLE_INTO <=", value, "isTriggerInsertableInto");
            return (Criteria) this;
        }

        public Criteria andIsTriggerInsertableIntoLike(String value) {
            addCriterion("IS_TRIGGER_INSERTABLE_INTO like", value, "isTriggerInsertableInto");
            return (Criteria) this;
        }

        public Criteria andIsTriggerInsertableIntoNotLike(String value) {
            addCriterion("IS_TRIGGER_INSERTABLE_INTO not like", value, "isTriggerInsertableInto");
            return (Criteria) this;
        }

        public Criteria andIsTriggerInsertableIntoIn(List<String> values) {
            addCriterion("IS_TRIGGER_INSERTABLE_INTO in", values, "isTriggerInsertableInto");
            return (Criteria) this;
        }

        public Criteria andIsTriggerInsertableIntoNotIn(List<String> values) {
            addCriterion("IS_TRIGGER_INSERTABLE_INTO not in", values, "isTriggerInsertableInto");
            return (Criteria) this;
        }

        public Criteria andIsTriggerInsertableIntoBetween(String value1, String value2) {
            addCriterion("IS_TRIGGER_INSERTABLE_INTO between", value1, value2, "isTriggerInsertableInto");
            return (Criteria) this;
        }

        public Criteria andIsTriggerInsertableIntoNotBetween(String value1, String value2) {
            addCriterion("IS_TRIGGER_INSERTABLE_INTO not between", value1, value2, "isTriggerInsertableInto");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table INFORMATION_SCHEMA.VIEWS
     *
     * @mbggenerated do_not_delete_during_merge Sat Mar 21 14:24:50 ICT 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table INFORMATION_SCHEMA.VIEWS
     *
     * @mbggenerated Sat Mar 21 14:24:50 ICT 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}